package com.xia.jobs.ws.autogen.attention;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri May 25 08:59:04 CST 2012
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://work.eac.cn/MyAttentionService/", name = "MyAttentionServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MyAttentionServicePortType {

    @WebResult(name = "getMyAttentionsResponse", targetNamespace = "http://work.eac.cn/MyAttentionService/", partName = "parameters")
    @WebMethod(action = "http://work.eac.cn/MyAttentionService/getMyAttentions")
    public GetMyAttentionsResponse getMyAttentions(
        @WebParam(partName = "parameters", name = "getMyAttentionsRequest", targetNamespace = "http://work.eac.cn/MyAttentionService/")
        GetMyAttentionsRequest parameters
    );
}
