(function(c,a){var g=this,e={mix:function(c,b,j,i,e){if(!b||!c)return c;j===a&&(j=!0);var g,n,o;if(i&&(o=i.length))for(g=0;g<o;g++)n=i[g],n in b&&d(n,c,b,j,e);else for(n in b)d(n,c,b,j,e);return c}},d=function(f,b,d,i,e){if(i||!(f in b)){var g=b[f],n=d[f];g!==n&&(e&&n&&(c.isArray(n)||c.isPlainObject(n))?(d=g&&(c.isArray(g)||c.isPlainObject(g))?g:c.isArray(n)?[]:{},b[f]=c.mix(d,n,i,a,!0)):n!==a&&(b[f]=d[f]))}},b=g&&g[c]||{},i=0,g=b.__HOST||(b.__HOST=g||{}),c=g[c]=e.mix(b,e,!1);c.mix(c,{__APP_MEMBERS:["namespace"],
__APP_INIT_METHODS:["__init"],version:"1.20dev",buildTime:"20110913201040",merge:function(){var a={},b,d=arguments.length;for(b=0;b<d;b++)c.mix(a,arguments[b]);return a},augment:function(){var b=c.makeArray(arguments),h=b.length-2,d=b[0],i=b[h],e=b[h+1],g=1;c.isArray(e)||(i=e,e=a,h++);c.isBoolean(i)||(i=a,h++);for(;g<h;g++)c.mix(d.prototype,b[g].prototype||b[g],i,e);return d},extend:function(a,b,d,i){if(!b||!a)return a;var e=Object.create?function(c,a){return Object.create(c,{constructor:{value:a}})}:
function(c,a){function b(){}b.prototype=c;var f=new b;f.constructor=a;return f},g=b.prototype,n;n=e(g,a);a.prototype=c.mix(n,a.prototype);a.superclass=e(g,b);d&&c.mix(n,d);i&&c.mix(a,i);return a},__init:function(){this.Config=this.Config||{};this.Env=this.Env||{};this.Config.debug="@DEBUG@"},namespace:function(){var f;var a=c.makeArray(arguments),b=a.length,d=null,i,e,m,n=!0===a[b-1]&&b--;for(i=0;i<b;i++){m=(""+a[i]).split(".");d=n?g:this;for(e=g[m[0]]===d?1:0;e<m.length;++e)f=d[m[e]]=d[m[e]]||{},
d=f}return d},app:function(a,b){var d=c.isString(a),i=d?g[a]||{}:a,e=0,m=c.__APP_INIT_METHODS.length;for(c.mix(i,this,!0,c.__APP_MEMBERS);e<m;e++)c[c.__APP_INIT_METHODS[e]].call(i);c.mix(i,c.isFunction(b)?b():b);d&&(g[a]=i);return i},config:function(c){for(var a in c)if(this["_"+a])this["_"+a](c[a])},log:function(b,d,j){if(c.Config.debug&&(j&&(b=j+": "+b),g.console!==a&&console.log))console[d&&console[d]?d:"log"](b)},error:function(a){if(c.Config.debug)throw a;},guid:function(c){return(c||"")+i++}});
c.__init();return c})("KISSY",void 0);
(function(c,a){function g(){if(B)return B;var a=q;c.each(G,function(c){a+=c+"|"});a=a.slice(0,-1);return B=RegExp(a,"g")}function e(){if(D)return D;var a=q;c.each(E,function(c){a+=c+"|"});a+="&#(\\d{1,5});";return D=RegExp(a,"g")}function d(c){var a=typeof c;return b(c)||"object"!==a&&"function"!==a}function b(a){return c.isNull(a)||c.isUndefined(a)}function i(a,b,f){var d=a,h,j,e,g;if(!a)return d;if(a[u])return f[a[u]].destination;if("object"===typeof a){g=a.constructor;if(c.inArray(g,[Boolean,String,
Number,Date,RegExp]))d=new g(a.valueOf());else if(h=c.isArray(a))d=b?c.filter(a,b):a.concat();else if(j=c.isPlainObject(a))d={};a[u]=g=c.guid();f[g]={destination:d,input:a}}if(h)for(a=0;a<d.length;a++)d[a]=i(d[a],b,f);else if(j)for(e in a)if(e!==u&&a.hasOwnProperty(e)&&(!b||b.call(a,a[e],e,a)!==k))d[e]=i(a[e],b,f);return d}function f(b,f,d,h){if(b[z]===f&&f[z]===b)return j;b[z]=f;f[z]=b;var i=function(c,b){return null!==c&&c!==a&&c[b]!==a},e;for(e in f)!i(b,e)&&i(f,e)&&d.push("expected has key '"+
e+"', but missing from actual.");for(e in b)!i(f,e)&&i(b,e)&&d.push("expected missing key '"+e+"', but present in actual.");for(e in f)e!=z&&(c.equals(b[e],f[e],d,h)||h.push("'"+e+"' was '"+(f[e]?f[e].toString():f[e])+"' in expected, but was '"+(b[e]?b[e].toString():b[e])+"' in actual."));c.isArray(b)&&c.isArray(f)&&b.length!=f.length&&h.push("arrays were not the same length");delete b[z];delete f[z];return 0===d.length&&0===h.length}var h=c.__HOST,j=!0,k=!1,l=Object.prototype,m=l.toString,n=l.hasOwnProperty,
l=Array.prototype,o=l.indexOf,p=l.lastIndexOf,r=l.filter,w=l.every,s=l.some,t=String.prototype.trim,v=l.map,q="",u="__~ks_cloned",z="__~ks_compared",I=/^\s+|\s+$/g,A=encodeURIComponent,y=decodeURIComponent,F={},G={"&amp;":"&","&gt;":">","&lt;":"<","&quot;":'"'},E={},B,D;(function(){for(var c in G)E[G[c]]=c})();c.mix(c,{noop:function(){},type:function(c){return b(c)?""+c:F[m.call(c)]||"object"},isNullOrUndefined:b,isNull:function(c){return null===c},isUndefined:function(c){return c===a},isEmptyObject:function(c){for(var b in c)if(b!==
a)return k;return j},isPlainObject:function(c){return c&&"[object Object]"===m.call(c)&&"isPrototypeOf"in c},equals:function(d,h,e,i){e=e||[];i=i||[];return d===h?j:d===a||null===d||h===a||null===h?b(d)&&b(h):d instanceof Date&&h instanceof Date?d.getTime()==h.getTime():c.isString(d)&&c.isString(h)||c.isNumber(d)&&c.isNumber(h)?d==h:"object"===typeof d&&"object"===typeof h?f(d,h,e,i):d===h},clone:function(b,f){var d={},h=i(b,f,d);c.each(d,function(b){b=b.input;if(b[u])try{delete b[u]}catch(d){c.log("delete CLONE_MARKER error : "),
b[u]=a}});d=a;return h},trim:t?function(c){return b(c)?q:t.call(c)}:function(c){return b(c)?q:c.toString().replace(I,q)},substitute:function(b,d,f){return!c.isString(b)||!c.isPlainObject(d)?b:b.replace(f||/\\?\{([^{}]+)\}/g,function(c,b){return"\\"===c.charAt(0)?c.slice(1):d[b]===a?q:d[b]})},each:function(b,d,f){if(b){var e,j=0,i=b&&b.length,g=i===a||"function"===c.type(b),f=f||h;if(g)for(e in b){if(d.call(f,b[e],e,b)===k)break}else for(e=b[0];j<i&&d.call(f,e,j,b)!==k;e=b[++j]);}return b},indexOf:o?
function(c,a){return o.call(a,c)}:function(c,a){for(var b=0,d=a.length;b<d;++b)if(a[b]===c)return b;return-1},lastIndexOf:p?function(c,a){return p.call(a,c)}:function(c,a){for(var b=a.length-1;0<=b&&!(a[b]===c);b--);return b},unique:function(a,b){var d=a.slice();b&&d.reverse();for(var f=0,h,e;f<d.length;){for(e=d[f];(h=c.lastIndexOf(e,d))!==f;)d.splice(h,1);f+=1}b&&d.reverse();return d},inArray:function(a,b){return-1<c.indexOf(a,b)},filter:r?function(c,a,b){return r.call(c,a,b||this)}:function(a,
b,d){var f=[];c.each(a,function(c,a,h){b.call(d||this,c,a,h)&&f.push(c)});return f},map:v?function(c,a,b){return v.call(c,a,b||this)}:function(a,b,d){for(var f=a.length,h=Array(f),e=0;e<f;e++){var j=c.isString(a)?a.charAt(e):a[e];if(j||e in a)h[e]=b.call(d||this,j,e,a)}return h},reduce:function(c,b,d){var f=c.length;if("function"!==typeof b)throw new TypeError("callback is not function!");if(0===f&&2==arguments.length)throw new TypeError("arguments invalid");var h=0,e;if(3<=arguments.length)e=arguments[2];
else{do{if(h in c){e=c[h++];break}h+=1;if(h>=f)throw new TypeError;}while(j)}for(;h<f;)h in c&&(e=b.call(a,e,c[h],h,c)),h++;return e},every:w?function(c,a,b){return w.call(c,a,b||this)}:function(c,a,b){for(var d=c&&c.length||0,f=0;f<d;f++)if(f in c&&!a.call(b,c[f],f,c))return k;return j},some:s?function(c,a,b){return s.call(c,a,b||this)}:function(c,a,b){for(var f=c&&c.length||0,d=0;d<f;d++)if(d in c&&a.call(b,c[d],d,c))return j;return k},bind:function(c,a){var b=[].slice,d=b.call(arguments,2),f=function(){},
h=function(){return c.apply(this instanceof f?this:a,d.concat(b.call(arguments)))};f.prototype=c.prototype;h.prototype=new f;return h},now:Date.now||function(){return+new Date},fromUnicode:function(c){return c.replace(/\\u([a-f\d]{4})/ig,function(c,a){return String.fromCharCode(parseInt(a,16))})},escapeHTML:function(c){return c.replace(g(),function(c){return E[c]})},unEscapeHTML:function(c){return c.replace(e(),function(c,a){return G[c]||String.fromCharCode(+a)})},makeArray:function(a){if(b(a))return[];
if(c.isArray(a))return a;if("number"!==typeof a.length||c.isString(a)||c.isFunction(a))return[a];for(var f=[],d=0,h=a.length;d<h;d++)f[d]=a[d];return f},param:function(a,b,f,h){if(!c.isPlainObject(a))return q;b=b||"&";f=f||"=";c.isUndefined(h)&&(h=j);var e=[],i,g;for(i in a)if(g=a[i],i=A(i),d(g))e.push(i,f,A(g+q),b);else if(c.isArray(g)&&g.length)for(var y=0,F=g.length;y<F;++y)d(g[y])&&e.push(i,h?A("[]"):q,f,A(g[y]+q),b);e.pop();return e.join(q)},unparam:function(a,b,f){if("string"!==typeof a||0===
(a=c.trim(a)).length)return{};for(var f=f||"=",d={},a=a.split(b||"&"),h,e,j=0,i=a.length;j<i;++j){b=a[j].split(f);h=y(b[0]);try{e=y(b[1]||q)}catch(g){c.log(g+"decodeURIComponent error : "+b[1],"error"),e=b[1]||q}c.endsWith(h,"[]")&&(h=h.substring(0,h.length-2));n.call(d,h)?c.isArray(d[h])?d[h].push(e):d[h]=[d[h],e]:d[h]=e}return d},later:function(a,b,f,d,h){var b=b||0,e=a,j=c.makeArray(h),i;c.isString(a)&&(e=d[a]);e||c.error("method undefined");a=function(){e.apply(d,j)};i=f?setInterval(a,b):setTimeout(a,
b);return{id:i,interval:f,cancel:function(){this.interval?clearInterval(i):clearTimeout(i)}}},startsWith:function(c,a){return 0===c.lastIndexOf(a,0)},endsWith:function(c,a){var b=c.length-a.length;return 0<=b&&c.indexOf(a,b)==b},throttle:function(a,b,f){b=b||150;if(-1===b)return function(){a.apply(f||this,arguments)};var d=c.now();return function(){var h=c.now();h-d>b&&(d=h,a.apply(f||this,arguments))}},buffer:function(a,b,f){function d(){d.stop();h=c.later(a,b,k,f||this)}b=b||150;if(-1===b)return function(){a.apply(f||
this,arguments)};var h=null;d.stop=function(){h&&(h.cancel(),h=0)};return d}});c.mix(c,{isBoolean:d,isNumber:d,isString:d,isFunction:d,isArray:d,isDate:d,isRegExp:d,isObject:d});c.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){F["[object "+a+"]"]=b=a.toLowerCase();c["is"+a]=function(a){return c.type(a)==b}})})(KISSY,void 0);(function(c){if(!("require"in this))c.__loader={},c.__loaderUtils={},c.__loaderData={}})(KISSY);
(function(c,a){"require"in this||c.mix(a,{LOADING:1,LOADED:2,ERROR:3,ATTACHED:4})})(KISSY,KISSY.__loaderData);
(function(c,a,g){if(!("require"in this)){var e=navigator.userAgent,d=document;c.mix(g,{docHead:function(){return d.getElementsByTagName("head")[0]||d.documentElement},isWebKit:!!e.match(/AppleWebKit/),IE:!!e.match(/MSIE/),isCss:function(a){return/\.css(?:\?|$)/i.test(a)},isLinkNode:function(a){return"link"==a.nodeName.toLowerCase()},normalizePath:function(a){for(var a=a.split("/"),c=[],b,d=0;d<a.length;d++)b=a[d],"."!=b&&(".."==b?c.pop():c.push(b));return c.join("/")},normalDepModuleName:function h(a,
d){if(!d)return d;if(c.isArray(d)){for(var e=0;e<d.length;e++)d[e]=h(a,d[e]);return d}if(b(d,"../")||b(d,"./")){var e="",g;if(-1!=(g=a.lastIndexOf("/")))e=a.substring(0,g+1);return i(e+d)}return-1!=d.indexOf("./")||-1!=d.indexOf("../")?i(d):d},removePostfix:function(a){return a.replace(/(-min)?\.js[^/]*$/i,"")},normalBasePath:function(d){"/"!=d.charAt(d.length-1)&&(d+="/");d=c.trim(d);!d.match(/^(http(s)?)|(file):/i)&&!b(d,"/")&&(d=a.__pagePath+d);return i(d)},indexMapping:function(a){for(var c=0;c<
a.length;c++)a[c].match(/\/$/)&&(a[c]+="index");return a}});var b=c.startsWith,i=g.normalizePath}})(KISSY,KISSY.__loader,KISSY.__loaderUtils);
(function(c,a){function g(){var a=!0,h;for(h in i){var j=i[h],k=j.node,j=j.callbacks,l=!1;if(e)k.sheet&&(c.log("webkit loaded : "+h),l=!0);else if(k.sheet)try{k.sheet.cssRules&&(c.log("firefox  "+k.sheet.cssRules+" loaded : "+h),l=!0)}catch(m){c.log("firefox  "+m.name+" "+h),"NS_ERROR_DOM_SECURITY_ERR"===m.name&&(c.log("firefox  "+m.name+" loaded : "+h),l=!0)}l?(c.each(j,function(a){a.call(k)}),delete i[h]):a=!1}a?(b=null,c.log("end css polling")):b=setTimeout(g,d)}if(!("require"in this)){var e=a.isWebKit,
d=100,b=null,i={};c.mix(a,{scriptOnload:document.addEventListener?function(c,b){if(a.isLinkNode(c))return a.styleOnload(c,b);c.addEventListener("load",b,!1)}:function(c,b){if(a.isLinkNode(c))return a.styleOnload(c,b);var d=c.onreadystatechange;c.onreadystatechange=function(){if(/loaded|complete/i.test(c.readyState))c.onreadystatechange=null,d&&d(),b.call(this)}},styleOnload:window.attachEvent?function(a,b){function d(){a.detachEvent("onload",d);c.log("ie/opera loaded : "+a.href);b.call(a)}a.attachEvent("onload",
d)}:function(a,d){var e=a.href;i[e]?i[e].callbacks.push(d):i[e]={node:a,callbacks:[d]};b||(c.log("start css polling"),g())}})}})(KISSY,KISSY.__loaderUtils);
(function(c,a){if(!("require"in this)){var g=a.scriptOnload;c.mix(c,{getStyle:function(e,d,b){var i=document,f=a.docHead(),i=i.createElement("link"),h=d;if(c.isPlainObject(h))d=h.success,b=h.charset;i.href=e;i.rel="stylesheet";if(b)i.charset=b;d&&a.scriptOnload(i,d);f.appendChild(i);return i},getScript:function(e,d,b){function i(){n&&(n.cancel(),n=void 0)}if(a.isCss(e))return c.getStyle(e,d,b);var f=document,h=f.head||f.getElementsByTagName("head")[0],j=f.createElement("script"),k=d,l,m,n;if(c.isPlainObject(k))d=
k.success,l=k.error,m=k.timeout,b=k.charset;j.src=e;j.async=!0;if(b)j.charset=b;if(d||l)g(j,function(){i();c.isFunction(d)&&d.call(j)}),c.isFunction(l)&&(f.addEventListener&&j.addEventListener("error",function(){i();l.call(j)},!1),n=c.later(function(){n=void 0;l()},1E3*(m||this.Config.timeout)));h.insertBefore(j,h.firstChild);return j}})}})(KISSY,KISSY.__loaderUtils);
(function(c,a,g,e){if(!("require"in this)){var d=g.IE,b=e.ATTACHED,i=c.mix;i(a,{add:function(a,h,e){var k=this.Env.mods,l;c.isString(a)&&!e&&c.isPlainObject(h)&&(l={},l[a]=h,a=l);if(c.isPlainObject(a))return c.each(a,function(a,c){a.name=c;k[c]&&i(a,k[c],!1)}),i(k,a),this;if(c.isString(a)){var m;if(e&&(m=e.host)){a=k[m];if(!a)return c.log("module "+m+" can not be found !","error"),this;this.__isAttached(m)?h.call(this,this):(a.fns=a.fns||[],a.fns.push(h));return this}this.__registerModule(a,h,e);
if(e&&!1===e.attach)return this;h=k[a];a=g.normalDepModuleName(a,h.requires);if(this.__isAttached(a))this.__attachMod(h);else if(this.Config.debug&&!h)for(a=(m=c.makeArray(a)).length-1;0<=a;a--)e=m[a],(k[e]||{}).status!==b&&c.log(h.name+" not attached when added : depends "+e);return this}if(c.isFunction(a))return e=h,h=a,d?(a=this.__findModuleNameByInteractive(),c.log("old_ie get modname by interactive : "+a),this.__registerModule(a,h,e),this.__startLoadModuleName=null,this.__startLoadTime=0):this.__currentModule=
{def:h,config:e},this;c.log("invalid format for KISSY.add !","error");return this}})}})(KISSY,KISSY.__loader,KISSY.__loaderUtils,KISSY.__loaderData);
(function(c,a,g,e){"require"in this||c.mix(a,{__buildPath:function(a,c){function i(e,i){!a[e]&&a[i]&&(a[i]=g.normalDepModuleName(a.name,a[i]),a[e]=(c||f.base)+a[i]);a[e]&&f.debug&&(a[e]=a[e].replace(/-min/ig,""));a[e]&&!a[e].match(/\?t=/)&&a.tag&&(a[e]+="?t="+a.tag)}var f=this.Config;i("fullpath","path");a.cssfullpath!==e.LOADED&&i("cssfullpath","csspath")}})})(KISSY,KISSY.__loader,KISSY.__loaderUtils,KISSY.__loaderData);
(function(c,a){"require"in this||c.mix(a,{__mixMods:function(a){var c=this.Env.mods,d=a.Env.mods,b;for(b in d)this.__mixMod(c,d,b,a)},__mixMod:function(a,e,d,b){var i=a[d]||{},f=i.status;c.mix(i,c.clone(e[d]));if(f)i.status=f;b&&this.__buildPath(i,b.Config.base);a[d]=i}})})(KISSY,KISSY.__loader);
(function(c,a,g){"require"in this||c.mix(a,{__findModuleNameByInteractive:function(){for(var a=document.getElementsByTagName("script"),d,b,i=0;i<a.length;i++)if(b=a[i],"interactive"==b.readyState){d=b;break}if(!d)return c.log("can not find interactive script,time diff : "+(+new Date-this.__startLoadTime),"error"),c.log("old_ie get modname from cache : "+this.__startLoadModuleName),this.__startLoadModuleName;a=d.src;c.log("interactive src :"+a);if(0===a.lastIndexOf(this.Config.base,0))return g.removePostfix(a.substring(this.Config.base.length));
d=this.__packages;for(var f in d)if(b=d[f].path,d.hasOwnProperty(f)&&0===a.lastIndexOf(b,0))return g.removePostfix(a.substring(b.length));c.log("interactive script not have package config \uff1a"+a,"error")}})})(KISSY,KISSY.__loader,KISSY.__loaderUtils);
(function(c,a,g,e){if(!("require"in this)){var d=g.IE,b=e.LOADING,i=e.LOADED,f=e.ERROR,h=e.ATTACHED;c.mix(a,{__load:function(a,e,l){function m(){c.log(a.name+" is not loaded! , can not find module in path : "+a.fullpath,"error");a.status=f}function n(){w[p]=i;if(a.status!==f){if(a.status!==h)a.status=i;e()}}var o=this,p=a.fullpath,r=g.isCss(p),w=o.Env._loadQueue,s=w[p];a.status=a.status||0;if(a.status<b&&s)a.status=s.nodeName?b:i;if(c.isString(a.cssfullpath))c.getScript(a.cssfullpath),a.cssfullpath=
a.csspath=i;if(a.status<b&&p){a.status=b;if(d&&!r)o.__startLoadModuleName=a.name,o.__startLoadTime=Number(+new Date);s=c.getScript(p,{success:function(){if(!r){if(o.__currentModule)c.log("standard browser get modname after load : "+a.name),o.__registerModule(a.name,o.__currentModule.def,o.__currentModule.config),o.__currentModule=null;l.global&&o.__mixMod(o.Env.mods,l.global.Env.mods,a.name,l.global);a.fns&&0<a.fns.length||m()}a.status!=f&&c.log(a.name+" is loaded.","info");n()},error:function(){m();
n()},charset:a.charset});w[p]=s}else a.status===b?g.scriptOnload(s,n):e()}})}})(KISSY,KISSY.__loader,KISSY.__loaderUtils,KISSY.__loaderData);(function(c,a,g){if(!("require"in this)){var e=g.ATTACHED,g=c.mix;g(a,{__pagePath:location.href.replace(location.hash,"").replace(/[^/]*$/i,""),__currentModule:null,__startLoadTime:0,__startLoadModuleName:null,__isAttached:function(a){var b=this.Env.mods,i=!0;c.each(a,function(a){a=b[a];if(!a||a.status!==e)return i=!1});return i}})}})(KISSY,KISSY.__loader,KISSY.__loaderData);
(function(c,a,g){"require"in this||c.mix(a,{_packages:function(a){var d;d=this.__packages=this.__packages||{};c.each(a,function(a){d[a.name]=a;a.path=a.path&&g.normalBasePath(a.path);a.tag=a.tag&&encodeURIComponent(a.tag)})},__getPackagePath:function(a){if(a.packagepath)return a.packagepath;var d=this._combine(a.name),b=this.__packages||{},i="",f;for(f in b)b.hasOwnProperty(f)&&c.startsWith(d,f)&&f.length>i&&(i=f);d=b[i];a.charset=d&&d.charset||a.charset;a.tag=d?d.tag:encodeURIComponent(c.Config.tag||
c.buildTime);return a.packagepath=d&&d.path||this.Config.base},_combine:function(a,d){var b=this,i;if(c.isObject(a))c.each(a,function(a,d){c.each(a,function(a){b._combine(a,d)})});else if(i=b.__combines=b.__combines||{},d)i[a]=d;else return i[a]||a}})})(KISSY,KISSY.__loader,KISSY.__loaderUtils);
(function(c,a,g){if(!("require"in this)){var e=g.LOADED,d=c.mix;d(a,{__registerModule:function(a,i,f){var f=f||{},h=this.Env.mods,j=h[a]||{};d(j,{name:a,status:e});j.fns&&j.fns.length&&c.log(a+" is defined more than once");j.fns=j.fns||[];j.fns.push(i);d(h[a]=j,f)}})}})(KISSY,KISSY.__loader,KISSY.__loaderData);
(function(c,a,g,e){if(!("require"in this)){var d=e.LOADED,b=e.ATTACHED;c.mix(a,{use:function(a,b,d){a=a.replace(/\s+/g,"").split(",");g.indexMapping(a);var d=d||{},e=this,k;d.global&&e.__mixMods(d.global);if(e.__isAttached(a)){var l=e.__getModules(a);b&&b.apply(e,l)}else return c.each(a,function(c){e.__attachModByName(c,function(){if(!k&&e.__isAttached(a)){k=!0;var c=e.__getModules(a);b&&b.apply(e,c)}},d)}),e},__getModules:function(a){var b=this,d=[b];c.each(a,function(a){g.isCss(a)||d.push(b.require(a))});
return d},require:function(a){var a=c.Env.mods[a],b=c.onRequire&&c.onRequire(a);return void 0!==b?b:a&&a.value},__attachModByName:function(a,d,e){var j=this.Env.mods,g=j[a];g||(g=this.Config.componentJsName||function(a){var c="js";if(/(.+)\.(js|css)$/i.test(a))c=RegExp.$2,a=RegExp.$1;return a+"-min."+c},g={path:c.isFunction(g)?g(this._combine(a)):g,charset:"utf-8"},j[a]=g);g.name=a;g&&g.status===b||this.__attach(g,d,e)},__attach:function(a,e,h){function j(){!n&&k.__isAttached(a.requires)&&(a.status===
d&&k.__attachMod(a),a.status===b&&(n=!0,e()))}var k=this,l=k.Env.mods,m=(a.requires||[]).concat();a.requires=m;c.each(m,function(c,d,e){c=e[d]=g.normalDepModuleName(a.name,c);(d=l[c])&&d.status===b||k.__attachModByName(c,j,h)});k.__buildPath(a,k.__getPackagePath(a));k.__load(a,function(){a.requires=a.requires||[];c.each(a.requires,function(d,e,f){d=f[e]=g.normalDepModuleName(a.name,d);e=l[d];f=c.inArray(d,m);e&&e.status===b||f||k.__attachModByName(d,j,h)});j()},h);var n=!1},__attachMod:function(a){var d=
this,e=a.fns;e&&c.each(e,function(b){b=c.isFunction(b)?b.apply(d,d.__getModules(a.requires)):b;a.value=a.value||b});a.status=b}})}})(KISSY,KISSY.__loader,KISSY.__loaderUtils,KISSY.__loaderData);
(function(c,a,g){function e(a){var e=a.src,h=a.getAttribute("data-combo-prefix")||"??",a=a.getAttribute("data-combo-sep")||",",a=e.split(a),g,k=a[0],h=k.indexOf(h);-1==h?g=e.replace(d,"$1"):(g=k.substring(0,h),e=k.substring(h+2,k.length),e.match(b)?g+=e.replace(d,"$1"):c.each(a,function(a){if(a.match(b))return g+=a.replace(d,"$1"),!1}));return g}if(!("require"in this)){c.mix(c,a);var d=/^(.*)(seed|kissy)(-aio)?(-min)?\.js[^/]*/i,b=/(seed|kissy)(-aio)?(-min)?\.js/i;c.__initLoader=function(){this.Env.mods=
this.Env.mods||{};this.Env._loadQueue={}};c.__initLoader();(function(){var a=document.getElementsByTagName("script"),a=e(a[a.length-1]);c.Config.base=g.normalBasePath(a);c.Config.timeout=10})();c.each(a,function(a,b){c.__APP_MEMBERS.push(b)});c.__APP_INIT_METHODS.push("__initLoader")}})(KISSY,KISSY.__loader,KISSY.__loaderUtils);
(function(c,a){function g(){var a=b.documentElement.doScroll,f=a?"onreadystatechange":"DOMContentLoaded",h=function(){e()};j=!0;if("complete"===b.readyState)e();else{if(b.addEventListener){var i=function(){b.removeEventListener(f,i,!1);e()};b.addEventListener(f,i,!1);d.addEventListener("load",h,!1)}else{var g=function(){"complete"===b.readyState&&(b.detachEvent(f,g),e())};b.attachEvent(f,g);d.attachEvent("onload",h);h=!1;try{h=null===d.frameElement}catch(l){c.log("frameElement error : "),c.log(l)}if(a&&
h){var m=function(){try{a("left"),e()}catch(c){setTimeout(m,k)}};m()}}return 0}}function e(){if(!f&&(f=!0,h)){for(var a,b=0;a=h[b++];)a.call(d,c);h=null}}var d=c.__HOST,b=d.document,i=b.documentElement,f=!1,h=[],j=!1,k=40,l=/^#?([\w-]+)$/,m=/\S/;c.mix(c,{isWindow:function(a){return"object"===c.type(a)&&"setInterval"in a&&"document"in a&&9==a.document.nodeType},parseXML:function(b){var d;try{window.DOMParser?d=(new DOMParser).parseFromString(b,"text/xml"):(d=new ActiveXObject("Microsoft.XMLDOM"),d.async=
"false",d.loadXML(b))}catch(e){c.log("parseXML error : "),c.log(e),d=a}(!d||!d.documentElement||d.getElementsByTagName("parsererror").length)&&c.error("Invalid XML: "+b);return d},globalEval:function(a){if(a&&m.test(a)){var c=b.getElementsByTagName("head")[0]||i,d=b.createElement("script");d.text=a;c.insertBefore(d,c.firstChild);c.removeChild(d)}},ready:function(a){j||g();f?a.call(d,this):h.push(a);return this},available:function(a,d){if((a=(a+"").match(l)[1])&&c.isFunction(d))var e=1,f=c.later(function(){(b.getElementById(a)&&
(d()||1)||500<++e)&&f.cancel()},k,!0)}});if(location&&-1!==(location.search||"").indexOf("ks-debug"))c.Config.debug=!0})(KISSY,void 0);(function(c){c.config({combine:{core:"dom,ua,event,node,json,ajax,anim,base,cookie".split(",")}})})(KISSY);
KISSY.add("ua/base",function(){var c=navigator.userAgent,a="",g="",e,d={},b=function(a){var c=0;return parseFloat(a.replace(/\./g,function(){return 0===c++?".":""}))};if((e=c.match(/AppleWebKit\/([\d.]*)/))&&e[1]){d[a="webkit"]=b(e[1]);if((e=c.match(/Chrome\/([\d.]*)/))&&e[1])d[g="chrome"]=b(e[1]);else if((e=c.match(/\/([\d.]*) Safari/))&&e[1])d[g="safari"]=b(e[1]);if(/ Mobile\//.test(c))d.mobile="apple";else if(e=c.match(/NokiaN[^\/]*|Android \d\.\d|webOS\/\d\.\d/))d.mobile=e[0].toLowerCase()}else if((e=
c.match(/Presto\/([\d.]*)/))&&e[1]){if(d[a="presto"]=b(e[1]),(e=c.match(/Opera\/([\d.]*)/))&&e[1]){d[g="opera"]=b(e[1]);if((e=c.match(/Opera\/.* Version\/([\d.]*)/))&&e[1])d[g]=b(e[1]);if((e=c.match(/Opera Mini[^;]*/))&&e)d.mobile=e[0].toLowerCase();else if((e=c.match(/Opera Mobi[^;]*/))&&e)d.mobile=e[0]}}else if((e=c.match(/MSIE\s([^;]*)/))&&e[1]){if(d[a="trident"]=0.1,d[g="ie"]=b(e[1]),(e=c.match(/Trident\/([\d.]*)/))&&e[1])d[a]=b(e[1])}else if(e=c.match(/Gecko/)){d[a="gecko"]=0.1;if((e=c.match(/rv:([\d.]*)/))&&
e[1])d[a]=b(e[1]);if((e=c.match(/Firefox\/([\d.]*)/))&&e[1])d[g="firefox"]=b(e[1])}d.core=a;d.shell=g;d._numberify=b;return d});
KISSY.add("ua/extra",function(c,a){var g=navigator.userAgent,e,d,b={},i=a._numberify;if(g.match(/360SE/))b[d="se360"]=3;else if(g.match(/Maxthon/)&&(e=window.external)){d="maxthon";try{b[d]=i(e.max_version)}catch(f){b[d]=0.1}}else if(e=g.match(/TencentTraveler\s([\d.]*)/))b[d="tt"]=e[1]?i(e[1]):0.1;else if(g.match(/TheWorld/))b[d="theworld"]=3;else if(e=g.match(/SE\s([\d.]*)/))b[d="sougou"]=e[1]?i(e[1]):0.1;d&&(b.shell=d);c.mix(a,b);return a},{requires:["ua/base"]});
KISSY.add("ua",function(c,a){return a},{requires:["ua/extra"]});
KISSY.add("dom/base",function(c,a){function g(a,c){return a&&a.nodeType===c}var e={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12,_isElementNode:function(a){return g(a,e.ELEMENT_NODE)},_getWin:function(c){return c&&"scrollTo"in c&&c.document?c:g(c,e.DOCUMENT_NODE)?c.defaultView||c.parentWindow:c===a||null===c?window:!1},
_nodeTypeIs:g,_isNodeList:function(a){return a&&!a.nodeType&&a.item&&!a.setTimeout}};return e});
KISSY.add("dom/attr",function(c,a,g,e){function d(a,c){var c=r[c]||c,b=s[c];return b&&b.get?b.get(a,c):a[c]}var g=document.documentElement,b=!g.hasAttribute,i=g.textContent===e?"innerText":"textContent",f=a._isElementNode,h=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,j=/^(?:button|input|object|select|textarea)$/i,k=/^a(?:rea)?$/i,l=/:|^on/,m=/\r/g,n={},o={val:1,css:1,html:1,text:1,data:1,width:1,height:1,offset:1},p=
{tabindex:{get:function(a){var c=a.getAttributeNode("tabindex");return c&&c.specified?parseInt(c.value,10):j.test(a.nodeName)||k.test(a.nodeName)&&a.href?0:e}},style:{get:function(a){return a.style.cssText},set:function(a,c){a.style.cssText=c}}},r={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},
w={get:function(c,b){return a.prop(c,b)?b.toLowerCase():e},set:function(c,b,d){!1===b?a.removeAttr(c,d):(b=r[d]||d,b in c&&(c[b]=!0),c.setAttribute(d,d.toLowerCase()));return d}},s={},t={},v={option:{get:function(a){var c=a.attributes.value;return!c||c.specified?a.value:a.text}},select:{get:function(c){var b=c.selectedIndex,d=c.options;if(0>b)return null;if("select-one"===c.type)return a.val(d[b]);for(var c=[],b=0,e=d.length;b<e;++b)d[b].selected&&c.push(a.val(d[b]));return c},set:function(b,d){var e=
c.makeArray(d);c.each(b.options,function(b){b.selected=c.inArray(a.val(b),e)});if(!e.length)b.selectedIndex=-1;return e}}};if(b)t={get:function(a,c){var b;return(b=a.getAttributeNode(c))&&""!==b.nodeValue?b.nodeValue:e},set:function(a,c,b){var d=a.getAttributeNode(b);if(d)d.nodeValue=c;else try{var e=a.ownerDocument.createAttribute(b);e.value=c;a.setAttributeNode(e)}catch(f){return a.setAttribute(b,c,0)}}},n=r,p.tabIndex=p.tabindex,c.each("href,src,width,height,colSpan,rowSpan".split(","),function(a){p[a]=
{get:function(c){c=c.getAttribute(a,2);return null===c?e:c}}}),v.button=p.value=t;c.each(["radio","checkbox"],function(b){v[b]={get:function(a){return null===a.getAttribute("value")?"on":a.value},set:function(b,d){if(c.isArray(d))return b.checked=c.inArray(a.val(b),d)}}});c.mix(a,{prop:function(b,f,h){if(c.isPlainObject(f))for(var i in f)a.prop(b,i,f[i]);else{var b=a.query(b),f=r[f]||f,g=s[f];if(h!==e)b.each(function(a){g&&g.set?g.set(a,h,f):a[f]=h});else if(b.length)return d(b[0],f)}},hasProp:function(c,
b){for(var f=a.query(c),h=0;h<f.length;h++)if(d(f[h],b)!==e)return!0;return!1},removeProp:function(b,d){d=r[d]||d;a.query(b).each(function(a){try{a[d]=e,delete a[d]}catch(b){c.log("delete el property error : "),c.log(b)}})},attr:function(b,d,i,g){if(c.isPlainObject(d)){var g=i,j;for(j in d)a.attr(b,j,d[j],g)}else if(d=c.trim(d)){d=d.toLowerCase();if(g&&o[d])return a[d](b,i);var d=n[d]||d,y;y=h.test(d)?w:l.test(d)?t:p[d];if(i===e){b=a.get(b);if(!f(b))return;"form"==b.nodeName.toLowerCase()&&(y=t);
if(y&&y.get)return y.get(b,d);b=b.getAttribute(d);return null===b?e:b}a.query(b).each(function(a){if(f(a)){var c=y;"form"==a.nodeName.toLowerCase()&&(c=t);c&&c.set?c.set(a,i,d):a.setAttribute(d,""+i)}})}},removeAttr:function(c,b){b=b.toLowerCase();b=n[b]||b;a.query(c).each(function(a){if(f(a)){var c;a.removeAttribute(b);if(h.test(b)&&(c=r[b]||b)in a)a[c]=!1}})},hasAttr:b?function(c,b){for(var b=b.toLowerCase(),d=a.query(c),e=0;e<d.length;e++){var f=d[e].getAttributeNode(b);if(f&&f.specified)return!0}return!1}:
function(c,b){for(var d=a.query(c),e=0;e<d.length;e++)if(d[e].hasAttribute(b))return!0;return!1},val:function(b,d){var f,h;if(d===e){var i=a.get(b);if(i){if((f=v[i.nodeName.toLowerCase()]||v[i.type])&&"get"in f&&(h=f.get(i,"value"))!==e)return h;h=i.value;return"string"===typeof h?h.replace(m,""):c.isNullOrUndefined(h)?"":h}}else a.query(b).each(function(a){if(1===a.nodeType){var b=d;c.isNullOrUndefined(b)?b="":"number"===typeof b?b+="":c.isArray(b)&&(b=c.map(b,function(a){return c.isNullOrUndefined(b)?
"":a+""}));f=v[a.nodeName.toLowerCase()]||v[a.type];if(!f||!("set"in f)||f.set(a,b,"value")===e)a.value=b}})},text:function(c,b){if(b===e){var d=a.get(c);return f(d)?d[i]||"":a._nodeTypeIs(d,a.TEXT_NODE)?d.nodeValue:e}a.query(c).each(function(c){if(f(c))c[i]=b;else if(a._nodeTypeIs(c,a.TEXT_NODE))c.nodeValue=b})}});return a},{requires:["./base","ua"]});
KISSY.add("dom/class",function(c,a,g){function e(b,e,h,j){if(!(e=c.trim(e)))return j?!1:g;for(var b=a.query(b),k=b.length,l=e.split(d),e=[],m=0;m<l.length;m++){var n=c.trim(l[m]);n&&e.push(n)}for(m=0;m<k;m++)if(l=b[m],a._isElementNode(l)&&(l=h(l,e,e.length),l!==g))return l;return j?!1:g}var d=/[\.\s]\s*\.?/,b=/[\n\t]/g;c.mix(a,{hasClass:function(a,c){return e(a,c,function(a,c,d){if(a=a.className){for(var a=(" "+a+" ").replace(b," "),e=0,f=!0;e<d;e++)if(0>a.indexOf(" "+c[e]+" ")){f=!1;break}if(f)return!0}},
!0)},addClass:function(a,d){e(a,d,function(a,e,i){var g=a.className;if(g){for(var m=(" "+g+" ").replace(b," "),n=0;n<i;n++)0>m.indexOf(" "+e[n]+" ")&&(g+=" "+e[n]);a.className=c.trim(g)}else a.className=d},g)},removeClass:function(a,d){e(a,d,function(a,d,e){var f=a.className;if(f)if(e){for(var f=(" "+f+" ").replace(b," "),i=0,g;i<e;i++)for(g=" "+d[i]+" ";0<=f.indexOf(g);)f=f.replace(g," ");a.className=c.trim(f)}else a.className=""},g)},replaceClass:function(c,b,d){a.removeClass(c,b);a.addClass(c,
d)},toggleClass:function(b,d,h){var j=c.isBoolean(h),k;e(b,d,function(c,b,d){for(var e=0,f;e<d;e++)f=b[e],k=j?!h:a.hasClass(c,f),a[k?"removeClass":"addClass"](c,f)},g)}});return a},{requires:["dom/base"]});
KISSY.add("dom/create",function(c,a,g,e){function d(c,b,e){if(b.nodeType==a.DOCUMENT_FRAGMENT_NODE)for(var b=b.childNodes,e=e.childNodes,f=0;b[f];)e[f]&&d(c,b[f],e[f]),f++;else if(b.nodeType==a.ELEMENT_NODE){b=b.getElementsByTagName("*");e=e.getElementsByTagName("*");for(f=0;b[f];)e[f]&&c(b[f],e[f]),f++}}function b(b,d){var e=c.require("event");if(d.nodeType===a.ELEMENT_NODE||a.hasData(b)){var f=a.data(b),h;for(h in f)a.data(d,h,f[h]);e&&(e._removeData(d),e._clone(b,d))}}function i(b,d){d.clearAttributes&&
d.clearAttributes();d.mergeAttributes&&d.mergeAttributes(b);var e=d.nodeName.toLowerCase();if("object"===e&&!d.childNodes.length)c.each(b.childNodes,function(a){d.appendChild(a)});else if("input"===e&&("checkbox"===b.type||"radio"===b.type)){if(b.checked)d.defaultChecked=d.checked=b.checked;if(d.value!==b.value)d.value=b.value}else if("option"===e)d.selected=b.defaultSelected;else if("input"===e||"textarea"===e)d.defaultValue=b.defaultValue;d.removeAttribute(a.__EXPANDO)}function f(b,d){c.isPlainObject(d)&&
(o(b)?a.attr(b,d,!0):b.nodeType==a.DOCUMENT_FRAGMENT_NODE&&c.each(b.childNodes,function(b){a.attr(b,d,!0)}));return b}function h(a,b){var d=null,e,f;if(a&&(a.push||a.item)&&a[0]){b=b||a[0].ownerDocument;d=b.createDocumentFragment();a.item&&(a=c.makeArray(a));for(e=0,f=a.length;e<f;e++)d.appendChild(a[e])}else c.log("Unable to convert "+a+" to fragment.");return d}function j(b,d){d=(d+"").replace(s,"");try{b.innerHTML=d}catch(e){c.log("set innerHTML error : ");for(c.log(e);b.firstChild;)b.removeChild(b.firstChild);
d&&b.appendChild(a.create(d))}}function k(b,d,e,f){if(e){var h=c.guid("ks-tmp-"),i=RegExp(s),d=d+('<span id="'+h+'"></span>');c.available(h,function(){var b=a.get("head"),e,g,j,y,k,A;for(i.lastIndex=0;e=i.exec(d);)if((j=(g=e[1])?g.match(v):!1)&&j[2]){e=l.createElement("script");e.src=j[2];if((y=g.match(q))&&y[2])e.charset=y[2];e.async=!0;b.appendChild(e)}else(A=e[2])&&0<A.length&&c.globalEval(A);(k=l.getElementById(h))&&a.remove(k);c.isFunction(f)&&f()});j(b,d)}else j(b,d),c.isFunction(f)&&f()}var l=
document,m=g.ie,n=a._nodeTypeIs,o=a._isElementNode,p=l.createElement("div"),r=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,w=/<(\w+)/,s=/<script([^>]*)>([^<]*(?:(?!<\/script>)<[^<]*)*)<\/script>/ig,t=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,v=/\ssrc=(['"])(.*?)\1/i,q=/\scharset=(['"])(.*?)\1/i;c.mix(a,{create:function(b,d,e){if(n(b,a.ELEMENT_NODE)||n(b,a.TEXT_NODE))return a.clone(b);if(!(b=c.trim(b)))return null;var i=null,g=a._creators,j,k="div",A;if(j=t.exec(b))i=(e||l).createElement(j[1]);
else{b=b.replace(r,"<$1></$2>");if((j=w.exec(b))&&(A=j[1]))k=A.toLowerCase();g=(g[k]||g.div)(b,e).childNodes;1===g.length?i=g[0].parentNode.removeChild(g[0]):g.length?i=h(g,e||l):c.error(b+" : create node error")}return f(i,d)},_creators:{div:function(a,b){var c=b?b.createElement("div"):p;c.innerHTML="m<div>"+a+"</div>";return c.lastChild}},html:function(b,c,d,f){if(c===e){if(b=a.get(b),o(b))return b.innerHTML}else a.query(b).each(function(a){o(a)&&k(a,c,d,f)})},remove:function(b,d){a.query(b).each(function(b){if(!d&&
b.nodeType==a.ELEMENT_NODE){var e=c.require("event");e&&(e.detach(b.getElementsByTagName("*")),e.detach(b));a.removeData(b.getElementsByTagName("*"));a.removeData(b)}b.parentNode&&b.parentNode.removeChild(b)})},clone:function(c,e,f,h){c=a.get(c);if(!c)return null;var g=c.cloneNode(e);if(c.nodeType==a.ELEMENT_NODE||c.nodeType==a.DOCUMENT_FRAGMENT_NODE)c.nodeType==a.ELEMENT_NODE&&i(c,g),e&&d(i,c,g);f&&(b(c,g),e&&h&&d(b,c,g));return g},_nl2frag:h});if(m||g.gecko||g.webkit){var u=a._creators,z=a.create,
I=/(?:\/(?:thead|tfoot|caption|col|colgroup)>)+\s*<tbody/,g={option:"select",td:"tr",tr:"tbody",tbody:"table",col:"colgroup",legend:"fieldset"},A;for(A in g)(function(a){u[A]=function(b,c){return z("<"+a+">"+b+"</"+a+">",null,c)}})(g[A]);if(8>m)u.tbody=function(a,b){var c=z("<table>"+a+"</table>",null,b),d=c.children.tags("tbody")[0];1<c.children.length&&d&&!I.test(a)&&d.parentNode.removeChild(d);return c};c.mix(u,{optgroup:u.option,th:u.td,thead:u.tbody,tfoot:u.tbody,caption:u.tbody,colgroup:u.tbody})}return a},
{requires:["./base","ua"]});
KISSY.add("dom/data",function(c,a,g){var e=window,d="_ks_data_"+c.now(),b={},i={},f={applet:1,object:1,embed:1},h={hasData:function(a,b){if(a)if(b!==g){if(b in a)return!0}else if(!c.isEmptyObject(a))return!0;return!1}},j={hasData:function(a,b){return a==e?j.hasData(i,b):h.hasData(a[d],b)},data:function(a,b,c){if(a==e)return j.data(i,b,c);var f=a[d];if(c!==g)f=a[d]=a[d]||{},f[b]=c;else return b!==g?f&&f[b]:f=a[d]=a[d]||{}},removeData:function(a,b){if(a==e)return j.removeData(i,b);var f=a[d];f&&(b!==
g?(delete f[b],c.isEmptyObject(f)&&j.removeData(a,g)):delete a[d])}},k={hasData:function(a,c){var e=a[d];return!e?!1:h.hasData(b[e],c)},data:function(a,e,h){if(!f[a.nodeName.toLowerCase()]){var i=a[d];i||(i=a[d]=c.guid());a=b[i];if(h!==g)a=b[i]=b[i]||{},a[e]=h;else return e!==g?a&&a[e]:a=b[i]=b[i]||{}}},removeData:function(a,e){var f=a[d];if(f){var h=b[f];if(h)if(e!==g)delete h[e],c.isEmptyObject(h)&&k.removeData(a,g);else{delete b[f];try{delete a[d]}catch(i){}a.removeAttribute&&a.removeAttribute(d)}}}};
c.mix(a,{__EXPANDO:d,hasData:function(b,c){for(var d=!1,e=a.query(b),f=0;f<e.length&&!(d=(d=e[f])&&d.nodeType?k.hasData(d,c):j.hasData(d,c));f++);return d},data:function(b,d,e){if(c.isPlainObject(d))for(var f in d)a.data(b,f,d[f]);else if(e===g){if((b=a.get(b))&&b.nodeType)return k.data(b,d,e);if(b)return j.data(b,d,e)}else a.query(b).each(function(a){a&&a.nodeType?k.data(a,d,e):j.data(a,d,e)})},removeData:function(b,c){a.query(b).each(function(a){a&&a.nodeType?k.removeData(a,c):j.removeData(a,c)})}});
return a},{requires:["./base"]});
KISSY.add("dom/insertion",function(c,a){function g(b,c,d){b=a.query(b);c=a.query(c);if(b.length&&c.length){var b=e(b),g;1<c.length&&(g=a.clone(b,!0));for(var k=0;k<c.length;k++){var l=c[k],m=0<k?a.clone(g,!0):b;d(m,l)}}}var e=a._nl2frag;c.mix(a,{insertBefore:function(a,b){g(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)})},insertAfter:function(a,b){g(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)})},appendTo:function(a,b){g(a,b,function(a,b){b.appendChild(a)})},
prependTo:function(a,b){g(a,b,function(a,b){b.insertBefore(a,b.firstChild)})}});var d={prepend:"prependTo",append:"appendTo",before:"insertBefore",after:"insertAfter"},b;for(b in d)a[b]=a[d[b]];return a},{requires:["./create"]});
KISSY.add("dom/offset",function(c,a,g,e){function d(b){var c,d=0;c=0;var e=f.body,i=m(b[r]);b[u]&&(c=b[u](),d=c[w],c=c[s],b=h&&9!=f.documentMode&&(n?j.clientTop:e.clientTop)||0,d-=h&&9!=f.documentMode&&(n?j.clientLeft:e.clientLeft)||0,c-=b,"apple"==g.mobile&&(d-=a[v](i),c-=a[q](i)));return{left:d,top:c}}function b(b,c){var e={left:0,top:0},f=m(b[r]),h=b,c=c||f;do{var g;if(f==c){var i=h;g=d(i);i=m(i[r]);g.left+=a[v](i);g.top+=a[q](i)}else g=d(h);e.left+=g.left;e.top+=g.top}while(f&&f!=c&&(h=f.frameElement)&&
(f=f.parent));return e}var i=window,f=document,h=g.ie,j=f.documentElement,k=a._isElementNode,l=a._nodeTypeIs,m=a._getWin,n="CSS1Compat"===f.compatMode,o=Math.max,p=parseInt,r="ownerDocument",w="left",s="top",t=c.isNumber,v="scrollLeft",q="scrollTop",u="getBoundingClientRect";c.mix(a,{offset:function(c,d,f){if(d===e){var c=a.get(c),h;c&&(h=b(c,f));return h}a.query(c).each(function(c){"static"===a.css(c,"position")&&(c.style.position="relative");var e=b(c),f={},h,g;for(g in d)h=p(a.css(c,g),10)||0,
f[g]=h+d[g]-e[g];a.css(c,f)})},scrollIntoView:function(b,c,d,f,h){if(b=a.get(b))if(!0!==h&&(f=f===e?!0:!!f,d=d===e?!0:!!d),!c||(c=a.get(c))===i)b.scrollIntoView(d);else{l(c,9)&&(c=m(c));var g=!!m(c),h=a.offset(b),j=g?{left:a.scrollLeft(c),top:a.scrollTop(c)}:a.offset(c),k=h[w]-j[w],n=h[s]-j[s],h=g?a.viewportHeight(c):c.clientHeight,j=g?a.viewportWidth(c):c.clientWidth,o=a[v](c),t=a[q](c),r=o+j,u=t+h,L=a.outerHeight(b),b=a.outerWidth(b),k=k+o-(g?0:p(a.css(c,"borderLeftWidth"))||0),g=n+t-(g?0:p(a.css(c,
"borderTopWidth"))||0),n=k+b,M=g+L,J,K;L>h||g<t||d?J=g:M>u&&(J=M-h);f&&(b>j||k<o||d?K=k:n>r&&(K=n-j));if(J!==e)a[q](c,J);if(K!==e)a[v](c,K)}},docWidth:0,docHeight:0,viewportHeight:0,viewportWidth:0});c.each(["Left","Top"],function(b,c){var d="scroll"+b;a[d]=function(f,h){if(t(f))return arguments.callee(i,f);var f=a.get(f),g,j=m(f);if(j)if(h!==e){var q="Left"==b?h:a.scrollLeft(j),l="Top"==b?h:a.scrollTop(j);j.scrollTo(q,l)}else{if(g=j["page"+(c?"Y":"X")+"Offset"],!t(g))j=j.document,g=j.documentElement[d],
t(g)||(g=j.body[d])}else k(f)&&(h!==e?f[d]=h:g=f[d]);return g}});c.each(["Width","Height"],function(b){a["doc"+b]=function(c){c=a.get(c);c=m(c).document;return o(c.documentElement["scroll"+b],c.body["scroll"+b],a["viewport"+b](c))};a["viewport"+b]=function(c){var c=a.get(c),d="inner"+b,c=m(c),e=c.document;return d in c?c[d]:n?e.documentElement["client"+b]:e.body["client"+b]}});return a},{requires:["./base","ua"]});
KISSY.add("dom/style",function(c,a,g,e){function d(a,b,c){var d={},e;for(e in b)d[e]=a[k][e],a[k][e]=b[e];c.call(a);for(e in b)a[k][e]=d[e]}function b(a,b,d){var f;if(3===a.nodeType||8===a.nodeType||!(f=a[k]))return e;var b=b.replace(p,r),h,g=v[b],b=q[b]||b;if(d!==e){null===d||d===s?d=s:!isNaN(Number(d))&&!o[b]&&(d+=t);g&&g.set&&(d=g.set(a,d));if(d!==e)try{a[k][b]=d}catch(i){c.log("css set error :"+i)}return e}if(!g||!("get"in g&&(h=g.get(a,!1))!==e))h=f[b];return h===e?"":h}function i(b,d,e){if(c.isWindow(b))return d==
l?a.viewportWidth(b):a.viewportHeight(b);if(9==b.nodeType)return d==l?a.docWidth(b):a.docHeight(b);var f=d===l?["Left","Right"]:["Top","Bottom"],h=d===l?b.offsetWidth:b.offsetHeight;if(0<h)return"border"!==e&&c.each(f,function(c){e||(h-=parseFloat(a.css(b,"padding"+c))||0);h="margin"===e?h+(parseFloat(a.css(b,e+c))||0):h-(parseFloat(a.css(b,"border"+c+"Width"))||0)}),h;h=a._getComputedStyle(b,d);if(0>h||c.isNullOrUndefined(h))h=b.style[d]||0;h=parseFloat(h)||0;e&&c.each(f,function(c){h+=parseFloat(a.css(b,
"padding"+c))||0;"padding"!==e&&(h+=parseFloat(a.css(b,"border"+c+"Width"))||0);"margin"===e&&(h+=parseFloat(a.css(b,e+c))||0)});return h}var f=document,h=f.documentElement,j=g.ie,k="style",l="width",m=parseInt,n=/^-?\d+(?:px)?$/i,o={fillOpacity:1,fontWeight:1,lineHeight:1,opacity:1,orphans:1,widows:1,zIndex:1,zoom:1},p=/-([a-z])/ig,r=function(a,b){return b.toUpperCase()},w=/([A-Z]|^ms)/g,s="",t="px",v={},q={},u={};h[k].cssFloat!==e?q["float"]="cssFloat":h[k].styleFloat!==e&&(q["float"]="styleFloat");
c.mix(a,{_CUSTOM_STYLES:v,_cssProps:q,_getComputedStyle:function(b,c){var d="",e={},f=b.ownerDocument,c=c.replace(w,"-$1").toLowerCase();if(e=f.defaultView.getComputedStyle(b,null))d=e.getPropertyValue(c)||e[c];""==d&&!a.__contains(f.documentElement,b)&&(c=q[c]||c,d=b[k][c]);return d},style:function(d,f,h){if(c.isPlainObject(f))for(var g in f)a.style(d,g,f[g]);else{if(h===e)return d=a.get(d),g="",d&&(g=b(d,f,h)),g;a.query(d).each(function(a){b(a,f,h)})}},css:function(b,d,f){if(c.isPlainObject(d))for(var h in d)a.css(b,
h,d[h]);else{d=d.replace(p,r);h=v[d];if(f===e){b=a.get(b);f="";if(b&&(!h||!("get"in h&&(f=h.get(b,!0))!==e)))f=a._getComputedStyle(b,d);return f===e?"":f}a.style(b,d,f)}},show:function(b){a.query(b).each(function(b){b[k].display=a.data(b,"display")||s;if("none"===a.css(b,"display")){var c=b.tagName,d=u[c],e;d||(e=f.createElement(c),f.body.appendChild(e),d=a.css(e,"display"),a.remove(e),u[c]=d);a.data(b,"display",d);b[k].display=d}})},hide:function(b){a.query(b).each(function(b){var c=b[k],d=c.display;
if("none"!==d)d&&a.data(b,"display",d),c.display="none"})},toggle:function(b){a.query(b).each(function(b){"none"===a.css(b,"display")?a.show(b):a.hide(b)})},addStyleSheet:function(b,d,e){c.isString(b)&&(e=d,d=b,b=window);var b=a.get(b),b=a._getWin(b).document,f;if(e&&(e=e.replace("#",s)))f=a.get("#"+e,b);if(!f)f=a.create("<style>",{id:e},b),a.get("head",b).appendChild(f),f.styleSheet?f.styleSheet.cssText=d:f.appendChild(b.createTextNode(d))},unselectable:function(b){a.query(b).each(function(a){if(g.gecko)a[k].MozUserSelect=
"none";else if(g.webkit)a[k].KhtmlUserSelect="none";else if(g.ie||g.opera){var b=0,c=a.getElementsByTagName("*");for(a.setAttribute("unselectable","on");a=c[b++];)switch(a.tagName.toLowerCase()){case "iframe":case "textarea":case "input":case "select":break;default:a.setAttribute("unselectable","on")}}})},innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0,width:0,height:0});c.each([l,"height"],function(b){a["inner"+(b.charAt(0).toUpperCase()+b.substring(1))]=function(c){return(c=a.get(c))?i(c,
b,"padding"):null};a["outer"+(b.charAt(0).toUpperCase()+b.substring(1))]=function(c,d){var e=a.get(c);return e?i(e,b,d?"margin":"border"):null};a[b]=function(c,d){var e=a.css(c,b,d);e&&(e=parseFloat(e));return e}});var z={position:"absolute",visibility:"hidden",display:"block"};c.each(["height","width"],function(a){v[a]={get:function(b,c){var e;if(c)return 0!==b.offsetWidth?e=i(b,a):d(b,z,function(){e=i(b,a)}),e+"px"},set:function(a,b){if(n.test(b)){if(b=parseFloat(b),0<=b)return b+"px"}else return b}}});
c.each(["left","top"],function(b){v[b]={get:function(d,e){if(e){var f=a._getComputedStyle(d,b);if("auto"===f){f=0;if(c.inArray(a.css(d,"position"),["absolute","fixed"])){f=d["left"===b?"offsetLeft":"offsetTop"];if(j&&9!=document.documentMode||g.opera)f-=d.offsetParent&&d.offsetParent["client"+("left"==b?"Left":"Top")]||0;f-=m(a.css(d,"margin-"+b))||0}f+="px"}return f}}}});return a},{requires:["dom/base","ua"]});
KISSY.add("dom/selector",function(c,a,g){function e(a,b){var f=[],h=b===g?[l]:e(b,g);o(h,function(b){s.apply(f,d(a,b))});(c.isString(a)&&-1<a.indexOf(",")||1<h.length)&&z(f);f.each=c.bind(o,g,f);return f}function d(a,d){var e=[];n("sizzle");v(a)&&(a=c.trim(a));if(v(a)&&-1<a.indexOf(","))e=b(a,d);else if(v(a)&&!u.exec(""+a)){var e=a,f=[],h=n("sizzle");h?h(e,d,f):k(e);e=f}else e=i(a,d);return e}function b(a,b){var c=[],e=a.split(",");o(e,function(a){s.apply(c,d(a,b))});return c}function i(b,c){var d,
e,g=[],i;if(v(b))if(q.test(b))(e=h(b.slice(1),c))&&(g=[e]);else{if(d=u.exec(b))if(e=d[1],i=d[2],d=d[3],c=e?h(e,c):c)d?!e||-1!=b.indexOf(t)?g=[].concat(I(d,i,c)):(e=h(e,c))&&a.hasClass(e,d)&&(g=[e]):i&&(g=j(i,c))}else b&&(p(b)||w(b))?g=m(b,function(a){return f(a,c)}):b&&f(b,c)&&(g=[b]);return g}function f(b,c){return!b?!1:c==l?!0:a.__contains(c,b)}function h(b,c){if(!c)return null;var d=c;if(c.nodeType!==a.DOCUMENT_NODE)d=c.ownerDocument;(d=d.getElementById(b))&&d.parentNode?a.attr(d,"id")!==b?d=a.filter("*",
"#"+b,c)[0]||null:f(d,c)||(d=null):d=null;return d}function j(a,b){return b&&r(b.getElementsByTagName(a))||[]}function k(a){c.error("Unsupported selector: "+a)}var l=document,m=c.filter,n=c.require,o=c.each,p=c.isArray,r=c.makeArray,w=a._isNodeList,s=Array.prototype.push,t=" ",v=c.isString,q=/^#[\w-]+$/,u=/^(?:#([\w-]+))?\s*([\w-]+|\*)?\.?([\w-]+)?$/,z;(function(){var a,b,c=!0;[0,0].sort(function(){c=!1;return 0});z=function(d){if(a&&(b=c,d.sort(a),b))for(var e=1,f=d.length;e<f;)d[e]===d[e-1]?d.splice(e,
1):e++;return d};a=l.documentElement.compareDocumentPosition?function(a,c){return a==c?(b=!0,0):!a.compareDocumentPosition||!c.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(c)&4?-1:1}:function(a,c){if(a==c)return b=!0,0;if(a.sourceIndex&&c.sourceIndex)return a.sourceIndex-c.sourceIndex}})();(function(){var a=l.createElement("div");a.appendChild(l.createComment(""));0<a.getElementsByTagName("*").length&&(j=function(a,b){var c=r(b.getElementsByTagName(a));if("*"===
a){for(var d=[],e=0,f;f=c[e++];)1===f.nodeType&&d.push(f);c=d}return c})})();var I=l.getElementsByClassName?function(a,b,c){if(!c)return[];var c=a=r(c.getElementsByClassName(a)),d=0,e=a.length,f;if(b&&"*"!==b)for(c=r();d<e;++d)f=a[d],f.nodeName.toLowerCase()==b.toLowerCase()&&c.push(f);return c}:l.querySelectorAll?function(a,b,c){return c&&r(c.querySelectorAll((b?b:"")+"."+a))||[]}:function(b,c,d){if(!d)return[];for(var c=r(d.getElementsByTagName(c||"*")),d=[],e=0,f=c.length,h;e<f;++e)h=c[e],a.hasClass(h,
b)&&d.push(h);return d};c.mix(a,{query:e,get:function(a,b){return e(a,b)[0]||null},unique:z,filter:function(b,d,f){var b=e(b,f),f=n("sizzle"),h,g,i,j,q=[];if(v(d)&&(h=u.exec(d)))i=h[1],g=h[2],j=h[3],i?i&&!g&&!j&&(d=function(a){return a.id===i}):d=function(b){var c=!0,d=!0;g&&(c=b.nodeName.toLowerCase()==g.toLowerCase());j&&(d=a.hasClass(b,j));return d&&c};c.isFunction(d)?q=c.filter(b,d):d&&f?q=f.matches(d,b):k(d);return q},test:function(b,c,d){b=e(b,d);return b.length&&a.filter(b,c,d).length===b.length}});
return a},{requires:["dom/base"]});
KISSY.add("dom/style-ie",function(c,a,g,e){if(!g.ie)return a;var d=document,b=d.documentElement,i=e._CUSTOM_STYLES,f=/^-?\d+(?:px)?$/i,h=/^-?\d/,j=/opacity=([^)]*)/,k=/alpha\([^)]*\)/i;try{c.isNullOrUndefined(b.style.opacity)&&(i.opacity={get:function(a,b){return j.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var b=parseFloat(b),d=a.style,e=a.currentStyle,f=isNaN(b)?"":"alpha(opacity="+100*b+")",h=c.trim(e&&e.filter||d.filter||
"");d.zoom=1;if(1<=b&&""===c.trim(h.replace(k,""))&&(d.removeAttribute("filter"),e&&!e.filter))return;d.filter=k.test(h)?h.replace(k,f):h+(h?", ":"")+f}})}catch(l){c.log("IE filters ActiveX is disabled. ex = "+l)}var g=8==g.ie,m={};m.thin=g?"1px":"2px";m.medium=g?"3px":"4px";m.thick=g?"5px":"6px";c.each(["","Top","Left","Right","Bottom"],function(a){var b="border"+a+"Width",c="border"+a+"Style";i[b]={get:function(a,d){var e=d?a.currentStyle:0,f=e&&""+e[b]||void 0;f&&0>f.indexOf("px")&&(f=m[f]&&"none"!==
e[c]?m[f]:0);return f}}});if(!(d.defaultView||{}).getComputedStyle&&b.currentStyle)a._getComputedStyle=function(b,c){var c=a._cssProps[c]||c,d=b.currentStyle&&b.currentStyle[c];if(!f.test(d)&&h.test(d)){var e=b.style,g=e.left,i=b.runtimeStyle&&b.runtimeStyle.left;i&&(b.runtimeStyle.left=b.currentStyle.left);e.left="fontSize"===c?"1em":d||0;d=e.pixelLeft+"px";e.left=g;i&&(b.runtimeStyle.left=i)}return""===d?"auto":d};return a},{requires:["./base","ua","./style"]});
KISSY.add("dom/traversal",function(c,a,g){function e(b,e,j,k,l,m){if(!(b=a.get(b)))return null;if(0===e)return b;m||(b=b[j]);if(!b)return null;l=l&&a.get(l)||null;e===g&&(e=1);var m=[],n=c.isArray(e),o,p;c.isNumber(e)&&(o=0,p=e,e=function(){return++o===p});for(;b&&b!=l;){if(i(b)&&d(b,e)&&(!k||k(b)))if(m.push(b),!n)break;b=b[j]}return n?m:m[0]||null}function d(b,d){if(!d)return!0;if(c.isArray(d))for(var e=0;e<d.length;e++){if(a.test(b,d[e]))return!0}else if(a.test(b,d))return!0;return!1}function b(b,
c,d){var e=[],g=b=a.get(b);if(b&&d)g=b.parentNode;if(g)for(d=0,g=g.firstChild;g;g=g.nextSibling)if(i(g)&&g!==b&&(!c||a.test(g,c)))e[d++]=g;return e}var i=a._isElementNode;c.mix(a,{closest:function(b,c,d){return e(b,c,"parentNode",function(b){return b.nodeType!=a.DOCUMENT_FRAGMENT_NODE},d,!0)},parent:function(b,c,d){return e(b,c,"parentNode",function(b){return b.nodeType!=a.DOCUMENT_FRAGMENT_NODE},d)},first:function(b,c){var d=a.get(b);return e(d&&d.firstChild,c,"nextSibling",g,g,!0)},last:function(b,
c){var d=a.get(b);return e(d&&d.lastChild,c,"previousSibling",g,g,!0)},next:function(a,b){return e(a,b,"nextSibling",g)},prev:function(a,b){return e(a,b,"previousSibling",g)},siblings:function(a,c){return b(a,c,!0)},children:function(a,c){return b(a,c,g)},__contains:document.documentElement.contains?function(b,c){if(b.nodeType==a.TEXT_NODE)return!1;var d;if(c.nodeType==a.TEXT_NODE)c=c.parentNode,d=!0;else{if(c.nodeType==a.DOCUMENT_NODE)return!1;d=b!==c}return d&&(b.contains?b.contains(c):!0)}:document.documentElement.compareDocumentPosition?
function(a,b){return!!(a.compareDocumentPosition(b)&16)}:0,contains:function(b,c){b=a.get(b);c=a.get(c);if(b&&c)return a.__contains(b,c)},equals:function(b,c){b=a.query(b);c=a.query(c);if(b.length!=c.length)return!1;for(var d=b.length;0<=d;d--)if(b[d]!=c[d])return!1;return!0}});return a},{requires:["./base"]});KISSY.add("dom",function(c,a){return a},{requires:"dom/attr,dom/class,dom/create,dom/data,dom/insertion,dom/offset,dom/style,dom/selector,dom/style-ie,dom/traversal".split(",")});
KISSY.add("event/keycodes",function(){var c={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90,META:91,
WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,WIN_KEY:224,
MAC_FF_META:224,WIN_IME:229};c.isTextModifyingKeyEvent=function(a){if(a.altKey&&!a.ctrlKey||a.metaKey||a.keyCode>=c.F1&&a.keyCode<=c.F12)return!1;switch(a.keyCode){case c.ALT:case c.CAPS_LOCK:case c.CONTEXT_MENU:case c.CTRL:case c.DOWN:case c.END:case c.ESC:case c.HOME:case c.INSERT:case c.LEFT:case c.MAC_FF_META:case c.META:case c.NUMLOCK:case c.NUM_CENTER:case c.PAGE_DOWN:case c.PAGE_UP:case c.PAUSE:case c.PHANTOM:case c.PRINT_SCREEN:case c.RIGHT:case c.SHIFT:case c.UP:case c.WIN_KEY:case c.WIN_KEY_RIGHT:return!1;
default:return!0}};c.isCharacterKey=function(a){if(a>=c.ZERO&&a<=c.NINE||a>=c.NUM_ZERO&&a<=c.NUM_MULTIPLY||a>=c.A&&a<=c.Z||goog.userAgent.WEBKIT&&0==a)return!0;switch(a){case c.SPACE:case c.QUESTION_MARK:case c.NUM_PLUS:case c.NUM_MINUS:case c.NUM_PERIOD:case c.NUM_DIVISION:case c.SEMICOLON:case c.DASH:case c.EQUALS:case c.COMMA:case c.PERIOD:case c.SLASH:case c.APOSTROPHE:case c.SINGLE_QUOTE:case c.OPEN_SQUARE_BRACKET:case c.BACKSLASH:case c.CLOSE_SQUARE_BRACKET:return!0;default:return!1}};return c});
KISSY.add("event/object",function(c,a){function g(a,c,d){this.currentTarget=a;this.originalEvent=c||{};c?(this.type=c.type,this._fix()):(this.type=d,this.target=a);this.currentTarget=a;this.fixed=!0}var e=document,d="altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" ");
c.augment(g,{_fix:function(){for(var b=this.originalEvent,c=d.length,f,h=this.currentTarget,h=9===h.nodeType?h:h.ownerDocument||e;c;)f=d[--c],this[f]=b[f];if(!this.target)this.target=this.srcElement||e;if(3===this.target.nodeType)this.target=this.target.parentNode;if(!this.relatedTarget&&this.fromElement)this.relatedTarget=this.fromElement===this.target?this.toElement:this.fromElement;if(this.pageX===a&&this.clientX!==a)b=h.documentElement,c=h.body,this.pageX=this.clientX+(b&&b.scrollLeft||c&&c.scrollLeft||
0)-(b&&b.clientLeft||c&&c.clientLeft||0),this.pageY=this.clientY+(b&&b.scrollTop||c&&c.scrollTop||0)-(b&&b.clientTop||c&&c.clientTop||0);if(this.which===a)this.which=this.charCode===a?this.keyCode:this.charCode;if(this.metaKey===a)this.metaKey=this.ctrlKey;if(!this.which&&this.button!==a)this.which=this.button&1?1:this.button&2?3:this.button&4?2:0},preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=!1;this.isDefaultPrevented=!0},stopPropagation:function(){var a=
this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;this.isPropagationStopped=!0},stopImmediatePropagation:function(){var a=this.originalEvent;a.stopImmediatePropagation?a.stopImmediatePropagation():this.stopPropagation();this.isImmediatePropagationStopped=!0},halt:function(a){a?this.stopImmediatePropagation():this.stopPropagation();this.preventDefault()}});return g});
KISSY.add("event/base",function(c,a,g,e){function d(a,b,d){if((d=c.trim(d))&&0<d.indexOf(l)){var f=h(arguments);c.each(d.split(l),function(c){var d=[].concat(f);d.splice(0,3,b,c);p[a].apply(p,d)});return!0}return e}function b(a){return a&&3!==a.nodeType&&8!==a.nodeType}function i(a,b,c,d,e){var f=p.special[b]||{};!d.length&&(!f.setup||!1===f.setup.call(a))&&j(a,b,c);f.add&&f.add.call(a,e)}var f=document,h=c.makeArray,j=f.addEventListener?function(a,b,c,d){a.addEventListener&&a.addEventListener(b,
c,!!d)}:function(a,b,c){a.attachEvent&&a.attachEvent("on"+b,c)},k=f.removeEventListener?function(a,b,c,d){a.removeEventListener&&a.removeEventListener(b,c,!!d)}:function(a,b,c){a.detachEvent&&a.detachEvent("on"+b,c)},l=" ",m="",n="trigger-none-"+c.now(),o="ksEventTargetId"+c.now(),p={_clone:function(b,d){if(d.nodeType===a.ELEMENT_NODE&&p._hasData(b)){var e=p._data(b).events;c.each(e,function(a,b){c.each(a,function(a){p.on(d,b,a.fn,a.scope,a.data)})})}},_hasData:function(b){return!!a.hasData(b,o)},
_data:function(b){var c=h(arguments);c.splice(1,0,o);return a.data.apply(a,c)},_removeData:function(b){var c=h(arguments);c.splice(1,0,o);return a.removeData.apply(a,c)},special:{},add:function(e,f,h,j,k){if(d("add",e,f,h,j,k))return e;a.query(e).each(function(a){var d=!a.isCustomEventTarget,e;if(a&&f&&c.isFunction(h)&&(!d||b(a))){(e=p._data(a))||p._data(a,e={});var l=e.events=e.events||{},l=l[f]=l[f]||[],n={fn:h,scope:j,data:k},o=e.handler;if(!o)o=e.handler=function(a,b){if(!(a&&a.type==m)){var d=
o.target;if(!a||!a.fixed)a=new g(d,a);c.isPlainObject(b)&&c.mix(a,b);return p._handle(d,a)}},o.target=a;d&&(i(a,f,o,l,n),a=null);l.push(n)}});return e},__getListeners:function(a,b){return(p.__getEvents(a)||{})[b]||[]},__getEvents:function(a){return(a=p._data(a))&&a.events},remove:function(f,h,g,i,j){if(d("remove",f,h,g,i))return f;a.query(f).each(function(a){var d=p._data(a),f=d&&d.events,m,l,n,o,r,E=!a.isCustomEventTarget,B=E&&p.special[h]||{};if(a&&(E||b(a))&&f)if(h===e)for(h in f)p.remove.call(p,
a,h);else{i=i||a;if(m=f[h]){l=m.length;if(g&&l){for(n=0,o=0,r=[];n<l;++n){var D=!1,x=m[n],H=x.scope||a;if(g!==x.fn||i!==H)r[o++]=x,D=!0;else if(j!==C){var C=x.data;!j&&C||C&&!j?(r[o++]=x,D=!0):j&&C&&(!j.equals||!C.equals?c.error("no equals in data"):C.equals(j)||(r[o++]=x,D=!0))}!D&&B.remove&&B.remove.call(a,x)}f[h]=r;l=r.length}if(g===e||0===l)E&&(!B.tearDown||!1===B.tearDown.call(a))&&k(a,h,d.handler),delete f[h]}if(c.isEmptyObject(f))d.handler.target=null,delete d.handler,delete d.events,p._removeData(a)}});
return f},_handle:function(a,b){for(var c=p.__getListeners(a,b.type).slice(0),d,f,h=0,g=c.length;h<g&&!(d=c[h],d=d.fn.call(d.scope||a,b,d.data),d!==e&&(!1!==f&&(f=d),!1===d&&b.halt()),b.isImmediatePropagationStopped);++h);return f},fire:function(f,h,i,j){if(!d("fire",f,h,i)){var k;a.query(f).each(function(a){var d=!a.isCustomEventTarget;i=i||{};i.type=h;if(d){var f=i,l;if(b(a)){d=new g(a);c.mix(d,f);j&&(d.stopPropagation(),d.preventDefault());var f=d.target=a,o="on"+h;do{var r=(p._data(f)||{}).handler;
d.currentTarget=f;r&&r.call(f,d);f[o]&&!1===f[o].call(f)&&(l=!1,d.preventDefault());f=f.parentNode||f.ownerDocument||f===a.ownerDocument&&window}while(f&&!d.isPropagationStopped);if(!d.isDefaultPrevented&&!("click"===h&&"a"==a.nodeName.toLowerCase())){var F;try{o&&a[h]&&((F=a[o])&&(a[o]=null),m=h,a[h]())}catch(G){c.log("trigger action error : "),c.log(G)}F&&(a[o]=F);m=n}}a=l;a!==e&&(k=a)}else(a=p._data(a))&&c.isFunction(a.handler)&&(k=a.handler(e,i))});return k}},_batchForType:d,_simpleAdd:j,_simpleRemove:k};
p.on=p.add;p.detach=p.remove;return p},{requires:["dom","event/object"]});KISSY.add("event/target",function(c,a){return{isCustomEventTarget:!0,fire:function(c,e){return a.fire(this,c,e)},on:function(c,e,d){a.add(this,c,e,d);return this},detach:function(c,e,d){a.remove(this,c,e,d);return this}}},{requires:["./base"]});
KISSY.add("event/focusin",function(c,a,g){a.ie||c.each([{name:"focusin",fix:"focus"},{name:"focusout",fix:"blur"}],function(a){function c(b){return g.fire(b.target,a.name)}var b=0;g.special[a.name]={setup:function(){0===b++&&document.addEventListener(a.fix,c,!0)},tearDown:function(){0===--b&&document.removeEventListener(a.fix,c,!0)}}});return g},{requires:["ua","./base"]});
KISSY.add("event/hashchange",function(c,a,g,e){e=b||e.ie;if(!("onhashchange"in window)||8>e){var d=window,b=document.documentMode,i=function(){return"#"+location.href.replace(/^[^#]*#?(.*)$/,"$1")},f,h=i(),j=function(){var a=i();a!==h&&(k(a),h=a);f=setTimeout(j,50)},k=8>e?function(a){var a="<html><body>"+a+"</body></html>",b=n.contentWindow.document;try{return b.open(),b.write(a),b.close(),!0}catch(d){return c.log("doc write error : "),c.log(d),!1}}:function(){a.fire(d,"hashchange")},l=function(){f||
j()},m=function(){f&&clearTimeout(f);f=null},n;8>e&&(l=function(){if(!n){n=g.create('<iframe style="display: none" height="0" width="0" tabindex="-1" title="empty"/>');g.prepend(n,document.documentElement);a.add(n,"load",function(){a.remove(n,"load");k(i());a.add(n,"load",b);j()});var b=function(){var b=c.trim(g.html(n.contentWindow.document.body)),e=i();if(b!=e)h=location.hash=b;a.fire(d,"hashchange")}}},m=function(){f&&clearTimeout(f);f=null;a.detach(n);g.remove(n);n=null});a.special.hashchange=
{setup:function(){this===d&&l()},tearDown:function(){this===d&&m()}}}},{requires:["./base","dom","ua"]});
KISSY.add("event/valuechange",function(c,a,g){function e(a){g.removeData(a,j);if(g.hasData(a,k)){var b=g.data(a,k);clearTimeout(b);g.removeData(a,k)}}function d(a){e(a.target)}function b(b){g.hasData(b,k)||g.data(b,k,setTimeout(function(){var c=b.value,d=g.data(b,j);c!==d&&(a.fire(b,h,{prevVal:d,newVal:c},!0),g.data(b,j,c));g.data(b,k,setTimeout(arguments.callee,l))},l))}function i(a){var c=a.target;"focus"==a.type&&g.data(c,j,c.value);b(c)}function f(b){e(b);a.remove(b,"blur",d);a.remove(b,"mousedown keyup keydown focus",
i)}var h="valuechange",j="event/valuechange/history",k="event/valuechange/poll",l=50;a.special[h]={setup:function(){var b=this.nodeName.toLowerCase();if("input"==b||"textarea"==b)f(this),a.on(this,"blur",d),a.on(this,"mousedown keyup keydown focus",i)},tearDown:function(){f(this)}};return a},{requires:["./base","dom"]});
KISSY.add("event/delegate",function(c,a,g){function e(a){return void 0===a.fn&&void 0===a.selector?!0:void 0===a.fn?this.selector==a.selector:this.fn==a.fn&&this.selector==a.selector&&this.scope==a.scope}function d(b,c){var d=a.closest(b.target,[c.selector],this),e;if(d)for(var f=0;f<d.length;f++){b.currentTarget=d[f];var g=c.fn.call(c.scope||this,b);if(!1===g||b.isPropagationStopped||b.isImmediatePropagationStopped)if(!1===g&&(e=g),b.isPropagationStopped||b.isImmediatePropagationStopped)break}return e}
function b(b,c){var d=b.target,e=b.relatedTarget;b.type=c.preType;if((d=a.closest(d,c.selector,this))&&d!==e&&(!e||!a.contains(d,e)))return b.currentTarget=d,c.fn.call(c.scope||this,b)}var i=g._batchForType,f={focus:{type:"focusin"},blur:{type:"focusout"},mouseenter:{type:"mouseover",handler:b},mouseleave:{type:"mouseout",handler:b}};c.mix(g,{delegate:function(b,c,k,l,m){if(i("delegate",b,c,k,l,m))return b;a.query(b).each(function(a){if(!a.isCustomEventTarget){var b=c,h=d;if(f[c])c=f[b].type,h=f[b].handler||
h;g.on(a,c,h,a,{fn:l,selector:k,preType:b,scope:m,equals:e})}});return b},undelegate:function(b,c,k,l,m){if(i("undelegate",b,c,k,l,m))return b;a.query(b).each(function(a){if(!a.isCustomEventTarget){var b=c,h=d;if(f[c])c=f[b].type,h=f[b].handler||h;g.remove(a,c,h,a,{fn:l,selector:k,preType:b,scope:m,equals:e})}});return b}});return g},{requires:["dom","./base"]});
KISSY.add("event/mouseenter",function(c,a,g,e){e.ie||c.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(d){function b(b){var e=b.relatedTarget;b.type=d.name;try{if(!e||e===document||e.parentNode)e!==this&&(!e||!g.contains(this,e))&&a._handle(this,b)}catch(h){c.log("withinElement error : "+h)}}a.special[d.name]={setup:function(){a.add(this,d.fix,b)},tearDown:function(){a.remove(this,d.fix,b)}}});return a},{requires:["./base","dom","ua"]});
KISSY.add("event",function(c,a,g,e,d){g.KeyCodes=a;g.Target=e;g.Object=d;return g},{requires:"event/keycodes,event/base,event/target,event/object,event/focusin,event/hashchange,event/valuechange,event/delegate,event/mouseenter".split(",")});
KISSY.add("node/base",function(c,a,g){function e(f,h,j){if(!(this instanceof e))return new e(f,h,j);if(f)if(c.isString(f)){if(f=a.create(f,h,j),f.nodeType===a.DOCUMENT_FRAGMENT_NODE)return d.push.apply(this,b(f.childNodes)),g}else{if(c.isArray(f)||i(f))return d.push.apply(this,b(f)),g}else return g;this[0]=f;this.length=1;return g}var d=Array.prototype,b=c.makeArray,i=a._isNodeList;c.augment(e,{length:0,item:function(a){return c.isNumber(a)?a>=this.length?null:new e(this[a]):new e(a)},add:function(a,
b,i){c.isNumber(b)&&(i=b,b=g);a=e.all(a,b).getDOMNodes();b=new e(this);i===g?d.push.apply(b,a):(i=[i,0],i.push.apply(i,a),d.splice.apply(b,i));return b},slice:function(a,b){return new e(d.slice.call(this,a,b))},getDOMNodes:function(){return d.slice.call(this)},each:function(a,b){var c=this.length,d=0,g;for(g=new e(this[0]);d<c&&!1!==a.call(b||g,g,d,this);g=new e(this[++d]));return this},getDOMNode:function(){return this[0]},end:function(){return this.__parent||this},all:function(a){a=0<this.length?
e.all(a,this):new e;a.__parent=this;return a},one:function(a){a=this.all(a);if(a=a.length?a.slice(0,1):null)a.__parent=this;return a}});c.mix(e,{ELEMENT_NODE:a.ELEMENT_NODE,ATTRIBUTE_NODE:a.ATTRIBUTE_NODE,TEXT_NODE:a.TEXT_NODE,CDATA_SECTION_NODE:a.CDATA_SECTION_NODE,ENTITY_REFERENCE_NODE:a.ENTITY_REFERENCE_NODE,ENTITY_NODE:a.ENTITY_NODE,PROCESSING_INSTRUCTION_NODE:a.PROCESSING_INSTRUCTION_NODE,COMMENT_NODE:a.COMMENT_NODE,DOCUMENT_NODE:a.DOCUMENT_NODE,DOCUMENT_TYPE_NODE:a.DOCUMENT_TYPE_NODE,DOCUMENT_FRAGMENT_NODE:a.DOCUMENT_FRAGMENT_NODE,
NOTATION_NODE:a.NOTATION_NODE,all:function(b,d){if(c.isString(b)&&(b=c.trim(b))&&3<=b.length&&c.startsWith(b,"<")&&c.endsWith(b,">")){if(d&&(d.getDOMNode&&(d=d.getDOMNode()),d.ownerDocument))d=d.ownerDocument;return new e(b,g,d)}return new e(a.query(b,d))},one:function(a,b){var c=e.all(a,b);return c.length?c.slice(0,1):null}});return e},{requires:["dom"]});
KISSY.add("node/attach",function(c,a,g,e,d){function b(b,c,e){e.unshift(c);b=a[b].apply(a,e);return b===d?c:b}var i=e.prototype,f=c.makeArray;c.each("equals,contains,scrollTop,scrollLeft,height,width,innerHeight,innerWidth,outerHeight,outerWidth,addStyleSheet,appendTo,prependTo,insertBefore,before,after,insertAfter,test,hasClass,addClass,removeClass,replaceClass,toggleClass,removeAttr,hasAttr,hasProp,scrollIntoView,remove,removeData,hasData,unselectable".split(","),function(a){i[a]=function(){var c=
f(arguments);return b(a,this,c)}});c.each("filter,first,parent,closest,next,prev,clone,siblings,children".split(","),function(b){i[b]=function(){var c;c=f(arguments);c.unshift(this);c=a[b].apply(a,c);c=c===d?this:null===c?null:new e(c);return c}});c.each({attr:1,text:0,css:1,style:1,val:0,prop:1,offset:0,html:0,data:1},function(e,g){i[g]=function(){var i;i=f(arguments);i[e]===d&&!c.isObject(i[0])?(i.unshift(this),i=a[g].apply(a,i)):i=b(g,this,i);return i}});c.each(["on","detach","fire","delegate",
"undelegate"],function(a){i[a]=function(){var b=f(arguments);b.unshift(this);return g[a].apply(g,b)}})},{requires:["dom","event","./base"]});KISSY.add("node/override",function(c,a,g,e){c.each(["append","prepend","before","after"],function(d){e.prototype[d]=function(b){c.isString(b)&&(b=a.create(b));if(b)a[d](b,this);return this}})},{requires:["dom","event","./base","./attach"]});
KISSY.add("anim/easing",function(){var c=Math.PI,a=Math.pow,g=Math.sin,e=1.70158,d={easeNone:function(a){return a},easeIn:function(a){return a*a},easeOut:function(a){return(2-a)*a},easeBoth:function(a){return 1>(a*=2)?0.5*a*a:0.5*(1- --a*(a-2))},easeInStrong:function(a){return a*a*a*a},easeOutStrong:function(a){return 1- --a*a*a*a},easeBothStrong:function(a){return 1>(a*=2)?0.5*a*a*a*a:0.5*(2-(a-=2)*a*a*a)},elasticIn:function(b){return 0===b||1===b?b:-(a(2,10*(b-=1))*g((b-0.075)*2*c/0.3))},elasticOut:function(b){return 0===
b||1===b?b:a(2,-10*b)*g((b-0.075)*2*c/0.3)+1},elasticBoth:function(b){return 0===b||2===(b*=2)?b:1>b?-0.5*a(2,10*(b-=1))*g((b-0.1125)*2*c/0.45):0.5*a(2,-10*(b-=1))*g((b-0.1125)*2*c/0.45)+1},backIn:function(a){1===a&&(a-=0.0010);return a*a*((e+1)*a-e)},backOut:function(a){return(a-=1)*a*((e+1)*a+e)+1},backBoth:function(a){return 1>(a*=2)?0.5*a*a*(((e*=1.525)+1)*a-e):0.5*((a-=2)*a*(((e*=1.525)+1)*a+e)+2)},bounceIn:function(a){return 1-d.bounceOut(1-a)},bounceOut:function(a){return a<1/2.75?7.5625*a*
a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},bounceBoth:function(a){return 0.5>a?0.5*d.bounceIn(2*a):0.5*d.bounceOut(2*a-1)+0.5},NativeTimeFunction:{easeNone:"linear",ease:"ease",easeIn:"ease-in",easeOut:"ease-out",easeBoth:"ease-in-out",easeInStrong:"cubic-bezier(0.9, 0.0, 0.9, 0.5)",easeOutStrong:"cubic-bezier(0.1, 0.5, 0.1, 1.0)",easeBothStrong:"cubic-bezier(0.9, 0.0, 0.1, 1.0)"}};return d});
KISSY.add("anim/manager",function(c){function a(a){a[g]=a[g]||c.guid("anim-");return a[g]}var g=c.guid("anim-");return{interval:20,runnings:{},timer:null,start:function(c){var d=a(c);this.runnings[d]||(this.runnings[d]=c,this.startTimer())},stop:function(a){this.notRun(a)},notRun:function(e){delete this.runnings[a(e)];c.isEmptyObject(this.runnings)&&this.stopTimer()},pause:function(a){this.notRun(a)},resume:function(a){this.start(a)},startTimer:function(){var a=this;if(!a.timer)a.timer=setTimeout(function(){a.runFrames()?
a.stopTimer():(a.timer=null,a.startTimer())},a.interval)},stopTimer:function(){var a=this.timer;if(a)clearTimeout(a),this.timer=null},runFrames:function(){var a=!0,c=this.runnings,b;for(b in c)c.hasOwnProperty(b)&&(a=!1,c[b]._runFrame());return a}}});
KISSY.add("anim/base",function(c,a,g,e,d,b,i){function f(b,d,g,h,j,p){if(b=a.get(b)){if(!(this instanceof f))return new f(b,d,g,h,j,p);p===i&&(p=!1);var r=c.isPlainObject(g);this.domEl=b;c.isPlainObject(d)&&(d=(""+c.param(d,";")).replace(/=/g,":").replace(/%23/g,"#").replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase());var s=d,E,B={},D=o.length,x;if(n(b)){x=a.clone(b,!0);a.insertAfter(x,b);E=x.style;for(l(x,s);D--;){var H=o[D];E[H]&&(B[H]=(t[H]||t["*"]).getter(x,H))}}else x=b;var s=m(s),C;for(C in s)B[C]=
x!==b?(t[C]||t["*"]).getter(x,C):k(s[C]);x!==b&&a.remove(x);this.props=B;this.targetStyle=d;if(r)r=c.merge(w,g);else{r=c.clone(w);if(null!=g)r.duration=parseFloat(g)||1;if(c.isString(h)||c.isFunction(h))r.easing=h;if(c.isFunction(j))r.complete=j;r.nativeSupport=p}if(r.nativeSupport&&!c.isEmptyObject(m(d)))r.nativeSupport=!1;this.config=r;if(r.nativeSupport&&v()&&c.isString(h=r.easing))if(/cubic-bezier\([\s\d.,]+\)/.test(h)||(h=e.NativeTimeFunction[h]))r.easing=h,this.transitionName=v();if(c.isFunction(j))this.callback=
j}}function h(a,b,c){return(a+(b-a)*c).toFixed(3)}function j(a,b){return b}function k(a){var b=parseFloat(a),a=(a+"").replace(/^[-\d.]+/,"");return isNaN(b)?{v:a,u:"",f:j}:{v:b,u:a,f:h}}function l(b,c){if(d.ie&&-1<c.indexOf(r)){var e=c.match(/opacity\s*:\s*([^;]+)(;|$)/);e&&a.css(b,r,parseFloat(e[1]))}n(b)&&(b.style.cssText+=";"+c);var e=m(c),f;for(f in e)(t[f]||t["*"]).setter(b,f,e[f])}function m(a){for(var b={},d=0;d<p.length;d++){var e=p[d].replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase();(e=a.match(RegExp(e+
"\\s*:([^;]+)(;|$)")))&&(b[p[d]]=c.trim(e[1]))}return b}var g=g.Target,n=a._isElementNode,o,p,r,w,s;o="borderBottomWidth borderBottomStyle borderLeftWidth borderLeftStyle borderRightWidth borderRightStyle borderSpacing borderTopWidth borderTopStyle bottom fontFamily fontSize fontWeight height left letterSpacing lineHeight marginBottom marginLeft marginRight marginTop maxHeight maxWidth minHeight minWidth opacity outlineOffset outlineWidth paddingBottom paddingLeft paddingRight paddingTop right textIndent top width wordSpacing zIndex".split(" ");
p=[];r="opacity";w={duration:1,easing:"easeNone",nativeSupport:!0};f.PROPS=o;f.CUSTOM_ATTRS=p;f.PROP_OPS={"*":{getter:function(b,c){return k(a.css(b,c))},setter:function(b,c,d){return a.css(b,c,d)},interpolate:h,eq:function(a,b){return a.v==b.v&&a.u==b.u}}};var t=f.PROP_OPS;c.augment(f,g,{isRunning:!1,elapsedTime:0,start:0,finish:0,duration:0,run:function(){var a=this,d=a.config,f=a.domEl,g,h=a.props,i={},j;if(!1!==a.fire("start")){a.stop();g=1E3*d.duration;a.duration=g;if(a.transitionName)setTimeout(function(){a._nativeRun()},
10);else{for(j in h)i[j]=(t[j]||t["*"]).getter(f,j);a.source=i;f=c.now();g=f+g;d=d.easing;c.isString(d)&&(d=e[d]||e.easeNone);a.start=f;a.finish=g;a.easing=d;b.start(a)}a.isRunning=!0;return a}},_complete:function(){this.fire("complete");this.callback&&this.callback()},_runFrame:function(){var a=this.domEl,b=this.finish,d=this.start,e=this.duration,f=c.now(),g=this.source,h=this.easing,i=this.props,k,d=f-d,e=f>b?1:d/e,l,m;this.elapsedTime=d;for(k in i){var d=g[k],n=l=i[k],o=d,p=t[k];if(!(p&&p.eq?
p.eq(n,o):t["*"].eq(n,o))){if(0===l.v)l.u=d.u;if(d.u!==l.u)d.v=0,d.u=l.u;n=l.f(d.v,l.v,h(e))+l.u;(t[k]||t["*"]).setter(a,k,n);if(l.f==j)d.v=l.v,d.u=l.u}}(!1===this.fire("step")||(m=f>b))&&this.stop(m)},_nativeRun:function(){var b=this,d=b.domEl,e=b.duration,f=b.config.easing,g=b.transitionName,h={};h[g+"Property"]="all";h[g+"Duration"]=e+"ms";h[g+"TimingFunction"]=f;a.css(d,h);setTimeout(function(){l(d,b.targetStyle)},0);c.later(function(){b.stop(!0)},e)},stop:function(a){if(this.isRunning)return this.transitionName?
this._nativeStop(a):(a&&(l(this.domEl,this.targetStyle),this._complete()),b.stop(this)),this.isRunning=!1,this},_nativeStop:function(b){var c=this.domEl,d=this.props,e;if(b)this._clearNativeProperty(),this._complete();else{for(e in d)a.css(c,e,a._getComputedStyle(c,e));this._clearNativeProperty()}},_clearNativeProperty:function(){var b={},c=this.domEl,d=this.transitionName;b[d+"Property"]="none";b[d+"Duration"]="";b[d+"TimingFunction"]="";a.css(c,b)}});f.supportTransition=function(){if(s)return s;
var a="transition",b,d=document.documentElement;d.style[a]!==i?b=a:c.each(["Webkit","Moz","O"],function(c){if(d.style[a=c+"Transition"]!==i)return b=a,!1});return s=b};var v=f.supportTransition;return f},{requires:["dom","event","./easing","ua","./manager"]});
KISSY.add("anim/color",function(c,a,g){function e(a){var a=a.toLowerCase(),d;if(d=a.match(f))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])];if(d=a.match(h)){for(a=1;a<d.length;a++)2>d[a].length&&(d[a]+=d[a]);return[parseInt(d[1],b),parseInt(d[2],b),parseInt(d[3],b)]}if(i[a])return i[a];c.log("only allow rgb or hex color string : "+a,"warn");return[255,255,255]}function d(a,b,c){var d=k["*"].interpolate;return"rgb("+[Math.floor(d(a[0],b[0],c)),Math.floor(d(a[1],b[1],c)),Math.floor(d(a[2],b[2],
c))].join(", ")+")"}var b=16,i={black:[0,0,0],silver:[192,192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255]},f=/^rgb\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\)$/i,h=/^#?([0-9A-F]{1,2})([0-9A-F]{1,2})([0-9A-F]{1,2})$/i,j="backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor color outlineColor".split(" "),
k=g.PROP_OPS,g=g.PROPS;g.push.apply(g,j);k.color={getter:function(b,c){return{v:e(a.css(b,c)),u:"",f:d}},setter:k["*"].setter,eq:function(a,b){return a.v+""==b.v+""}};c.each(j,function(a){k[a]=k.color})},{requires:["dom","./base"]});KISSY.add("anim/scroll",function(c,a,g){var e=g.PROP_OPS;g.CUSTOM_ATTRS.push("scrollLeft","scrollTop");e.scrollLeft=e.scrollTop={getter:function(c,b){return{v:a[b](c),u:"",f:e["*"].interpolate}},setter:function(c,b,e){a[b](c,e)}}},{requires:["dom","./base"]});
KISSY.add("anim",function(c,a,g){a.Easing=g;return a},{requires:["anim/base","anim/easing","anim/color","anim/scroll"]});
KISSY.add("node/anim-plugin",function(c,a,g,e,d){function b(b,e,f,i,s,t,v){s&&a.show(b);var q={},u={};c.each(n[e],function(c){var d=b.style;if(c===h)q[h]=d[h],a.css(b,h,j);else if(c===k)q[k]=a.style(b,k),u.opacity=s?1:0,s&&a.css(b,k,0);else if(c===l)q[l]=d[l],u.height=(s?a.height(b)||b.naturalHeight:0)+"px",s&&a.css(b,l,0);else if(c===m)q[m]=d[m],u.width=(s?a.width(b)||b.naturalWidth:0)+"px",s&&a.css(b,m,0)});return(new g(b,u,f,t,function(){s||a.hide(b);q[l]!==d&&a.css(b,"height",q[l]);q[m]!==d&&
a.css(b,"width",q[m]);q[k]!==d&&a.css(b,"opacity",q[k]);q[h]!==d&&a.css(b,"overflow",q[h]);i&&i()},v)).run()}var i=e.prototype,f="ksAnims"+c.now(),h="overflow",j="hidden",k="opacity",l="height",m="width",n={show:[h,k,l,m],fade:[k],slide:[h,l]};e.__ANIM_KEY=f;(function(e){function h(b,d){var e=a.data(b,f);e||a.data(b,f,e=[]);d.on("complete",function(){var e=a.data(b,f);if(e){var g=c.indexOf(d,e);0<=g&&e.splice(g,1);e.length||a.removeData(b,f)}});e.push(d)}e.animate=function(){var a=c.makeArray(arguments);
c.each(this,function(b){var c=g.apply(d,[b].concat(a)).run();h(b,c)});return this};e.stop=function(b){c.each(this,function(d){var e=a.data(d,f);e&&(c.each(e,function(a){a.stop(b)}),a.removeData(d,f))});return this};c.each({show:["show",1],hide:["show",0],fadeIn:["fade",1],fadeOut:["fade",0],slideDown:["slide",1],slideUp:["slide",0]},function(d,f){e[f]=function(e,g,i,j){if(a[f]&&!e)a[f](this);else c.each(this,function(a){var c=b(a,d[0],e,g,d[1],i||"easeOut",j);h(a,c)});return this}});e.toggle=function(a){e["none"===
this.css("display")?"show":"hide"].apply(this,arguments)}})(i)},{requires:["dom","anim","./base"]});KISSY.add("node",function(c,a,g){g.KeyCodes=a.KeyCodes;return g},{requires:["event","node/base","node/attach","node/override","node/anim-plugin"]});
KISSY.add("json/json2",function(c,a){function g(a){return 10>a?"0"+a:a}function e(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=l[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,b){var c,f,g,h,i=j,l,q=b[a];q&&"object"===typeof q&&"function"===typeof q.toJSON&&(q=q.toJSON(a));"function"===typeof m&&(q=m.call(b,a,q));switch(typeof q){case "string":return e(q);case "number":return isFinite(q)?""+q:"null";case "boolean":case "null":return""+
q;case "object":if(!q)return"null";j+=k;l=[];if("[object Array]"===Object.prototype.toString.apply(q)){h=q.length;for(c=0;c<h;c+=1)l[c]=d(c,q)||"null";g=0===l.length?"[]":j?"[\n"+j+l.join(",\n"+j)+"\n"+i+"]":"["+l.join(",")+"]";j=i;return g}if(m&&"object"===typeof m){h=m.length;for(c=0;c<h;c+=1)f=m[c],"string"===typeof f&&(g=d(f,q))&&l.push(e(f)+(j?": ":":")+g)}else for(f in q)Object.hasOwnProperty.call(q,f)&&(g=d(f,q))&&l.push(e(f)+(j?": ":":")+g);g=0===l.length?"{}":j?"{\n"+j+l.join(",\n"+j)+"\n"+
i+"}":"{"+l.join(",")+"}";j=i;return g}}var b=window,i=b.JSON;if(!i||9>a.ie)i=b.JSON={};if("function"!==typeof Date.prototype.toJSON)Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+g(this.getUTCMonth()+1)+"-"+g(this.getUTCDate())+"T"+g(this.getUTCHours())+":"+g(this.getUTCMinutes())+":"+g(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,j,k,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;if("function"!==typeof i.stringify)i.stringify=function(a,b,c){var e;k=j="";if("number"===typeof c)for(e=0;e<c;e+=1)k+=" ";else"string"===typeof c&&(k=c);if((m=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return d("",{"":a})};
if("function"!==typeof i.parse)i.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&"object"===typeof g)for(e in g)Object.hasOwnProperty.call(g,e)&&(f=c(g,e),void 0!==f?g[e]=f:delete g[e]);return b.call(a,d,g)}var d,a=""+a;f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,
"")))return d=eval("("+a+")"),"function"===typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");};return i},{requires:["ua"]});KISSY.add("json",function(c,a){return{parse:function(g){return c.isNullOrUndefined(g)||""===g?null:a.parse(g)},stringify:a.stringify}},{requires:["json/json2"]});
KISSY.add("ajax/form-serializer",function(c,a){var g=/^(?:select|textarea)/i,e=/\r?\n/g,d=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i;return{serialize:function(b){var i=[],f={};a.query(b).each(function(a){a=a.elements?c.makeArray(a.elements):[a];i.push.apply(i,a)});i=c.filter(i,function(a){return a.name&&!a.disabled&&(a.checked||g.test(a.nodeName)||d.test(a.type))});c.each(i,function(b){var d=a.val(b),d=c.map(c.makeArray(d),function(a){return a.replace(e,
"\r\n")}),b=f[b.name]=f[b.name]||[];b.push.apply(b,d)});return c.param(f,void 0,void 0,!1)}}},{requires:["dom"]});
KISSY.add("ajax/xhrobject",function(c,a){function g(a){var d=a.responseText,e=a.responseXML,g=a.config,j=g.converters,k=a.converters||{},l,m,n=g.contents,o=g.dataType;if(d||e){for(g=a.mimeType||a.getResponseHeader("Content-Type");"*"==o[0];)o.shift();if(!o.length)for(l in n)if(n[l].test(g)){o[0]!=l&&o.unshift(l);break}o[0]=o[0]||"text";"text"==o[0]&&void 0!==d?m=d:"xml"==o[0]&&void 0!==e?m=e:c.each(["text","xml"],function(a){var b=o[0];if(k[a]&&k[a][b]||j[a]&&j[a][b])return o.unshift(a),m="text"==
a?d:e,!1})}n=o[0];for(g=1;g<o.length;g++){l=o[g];var p=k[n]&&k[n][l]||j[n]&&j[n][l];if(!p)throw"no covert for "+n+" => "+l;m=p(m);n=l}a.responseData=m}function e(a){c.mix(this,{responseData:null,config:a||{},timeoutTimer:null,responseText:null,responseXML:null,responseHeadersString:"",responseHeaders:null,requestHeaders:{},readyState:0,state:0,statusText:null,status:0,transport:null})}var d=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg;c.augment(e,a.Target,{setRequestHeader:function(a,c){this.requestHeaders[a]=
c;return this},getAllResponseHeaders:function(){return 2===this.state?this.responseHeadersString:null},getResponseHeader:function(a){var c;if(2===this.state){if(!this.responseHeaders)for(this.responseHeaders={};c=d.exec(this.responseHeadersString);)this.responseHeaders[c[1]]=c[2];c=this.responseHeaders[a]}return void 0===c?null:c},overrideMimeType:function(a){if(!this.state)this.mimeType=a;return this},abort:function(a){a=a||"abort";this.transport&&this.transport.abort(a);this.callback(0,a);return this},
callback:function(a,c){if(2!=this.state){this.state=2;this.readyState=4;var d;if(200<=a&&300>a||304==a)if(304==a)c="notmodified",d=!0;else try{g(this),c="success",d=!0}catch(e){c="parsererror : "+e}else 0>a&&(a=0);this.status=a;this.statusText=c;d?this.fire("success"):this.fire("error");this.fire("complete");this.transport=void 0}}});return e},{requires:["event"]});
KISSY.add("ajax/base",function(c,a,g,e){function d(a){a=c.mix(c.clone(s),a||{},void 0,void 0,!0);if(!c.isBoolean(a.crossDomain)){var b=j.exec(a.url.toLowerCase());a.crossDomain=!(!b||!(b[1]!=p[1]||b[2]!=p[2]||(b[3]||("http:"===b[1]?l:m))!=(p[3]||("http:"===p[1]?l:m))))}if(a.processData&&a.data&&!c.isString(a.data))a.data=c.param(a.data,void 0,void 0,a.serializeArray);a.type=a.type.toUpperCase();a.hasContent=!n.test(a.type);a.hasContent||(a.data&&(a.url+=(/\?/.test(a.url)?"&":"?")+a.data),!1===a.cache&&
(a.url+=(/\?/.test(a.url)?"&":"?")+"_ksTS="+(c.now()+"_"+c.guid())));a.dataType=c.trim(a.dataType||"*").split(h);a.context=a.context||a;return a}function b(a,b){f.fire(a,{ajaxConfig:b.config,xhr:b})}function i(a){var c=this.config,a=a.type;this.timeoutTimer&&clearTimeout(this.timeoutTimer);c[a]&&c[a].call(c.context,this.responseData,this.statusText,this);b(a,this)}function f(a){if(a.url){var a=d(a),f=new e(a);b("start",f);var g=new (w[a.dataType[0]]||w["*"])(f);f.transport=g;a.contentType&&f.setRequestHeader("Content-Type",
a.contentType);var h=a.dataType[0],j=a.accepts;f.setRequestHeader("Accept",h&&j[h]?j[h]+("*"===h?"":", */*; q=0.01"):j["*"]);for(var k in a.headers)f.setRequestHeader(k,a.headers[k]);f.on("complete success error",i);f.readyState=1;b("send",f);if(a.async&&0<a.timeout)f.timeoutTimer=setTimeout(function(){f.abort("timeout")},a.timeout);try{f.state=1,g.send()}catch(l){2>f.status?f.callback(-1,l):c.error(l)}return f}}var h=/\s+/,j=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,k=function(a){return a},
l=80,m=443,n=/^(?:GET|HEAD)$/,o,p;try{o=location.href}catch(r){c.log("ajax/base get curLocation error : "),c.log(r),o=document.createElement("a"),o.href="",o=o.href}p=j.exec(o);o=/^(?:about|app|app\-storage|.+\-extension|file|widget):$/.test(p[1]);var w={},s={type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",async:!0,serializeArray:!0,processData:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":"*/*"},
converters:{text:{json:a.parse,html:k,text:k,xml:c.parseXML}},contents:{xml:/xml/,html:/html/,json:/json/}};s.converters.html=s.converters.text;c.mix(f,g.Target);c.mix(f,{isLocal:o,setupConfig:function(a){c.mix(s,a,void 0,void 0,!0)},setupTransport:function(a,b){w[a]=b},getTransport:function(a){return w[a]},getConfig:function(){return s}});return f},{requires:["json","event","./xhrobject"]});
KISSY.add("ajax/xdr",function(c,a){function g(a,c,d){if(!h)h=!0,a='<object id="'+b+'" type="application/x-shockwave-flash" data="'+a+'" width="0" height="0"><param name="movie" value="'+a+'" /><param name="FlashVars" value="yid='+c+"&uid="+d+'&host=KISSY.io" /><param name="allowScriptAccess" value="always" /></object>',c=f.createElement("div"),f.body.appendChild(c),c.innerHTML=a}function e(a){c.log("use flash xdr");this.xhrObj=a}var d={},b="io_swf",i,f=document,h=!1;c.augment(e,{send:function(){var a=
this,b=a.xhrObj.config;g((b.xdr||{}).src||c.Config.base+"ajax/io.swf",1,1);i?(a._uid=c.guid(),d[a._uid]=a,i.send(b.url,{id:a._uid,uid:a._uid,method:b.type,data:b.hasContent&&b.data||{}})):setTimeout(function(){a.send()},200)},abort:function(){i.abort(this._uid)},_xdrResponse:function(a,b){var c,e=this.xhrObj;e.responseText=decodeURI(b.c.responseText);switch(a){case "success":c={status:200,statusText:"success"};delete d[b.id];break;case "abort":delete d[b.id];break;case "timeout":case "transport error":case "failure":delete d[b.id],
c={status:500,statusText:a}}c&&e.callback(c.status,c.statusText)}});a.applyTo=function(a,b,d){var a=b.split("."),e=c;c.each(a,function(a){e=e[a]});e.apply(null,d)};a.xdrReady=function(){i=f.getElementById(b)};a.xdrResponse=function(a,b,c){var e=d[b.uid];e&&e._xdrResponse(a,b,c)};c.io=a;return e},{requires:["./base"]});
KISSY.add("ajax/xhr",function(c,a,g){function e(){try{return new window.XMLHttpRequest}catch(a){c.log("createStandardXHR error")}}var d=window.XDomainRequest;a.xhr=window.ActiveXObject?function(b){if(b&&d)b=new d;else if(!(b=!a.isLocal&&e()))a:{try{b=new window.ActiveXObject("Microsoft.XMLHTTP");break a}catch(g){c.log("createActiveXHR error")}b=void 0}return b}:e;var b=a.xhr();if(b){var i=function(a){var c=a.config,e=c.xdr||{};if(c.crossDomain&&!("withCredentials"in b)&&("flash"===""+e.use||!d))return new g(a);
this.xhrObj=a};c.augment(i,{send:function(){var b=this,e=b.xhrObj,g=e.config,i=a.xhr(g.crossDomain),l,m;b.xhr=i;g.username?i.open(g.type,g.url,g.async,g.username,g.password):i.open(g.type,g.url,g.async);if(l=g.xhrFields)for(m in l)i[m]=l[m];e.mimeType&&i.overrideMimeType&&i.overrideMimeType(e.mimeType);!g.crossDomain&&!e.requestHeaders["X-Requested-With"]&&(e.requestHeaders["X-Requested-With"]="XMLHttpRequest");try{if(!g.crossDomain)for(m in e.requestHeaders)i.setRequestHeader(m,e.requestHeaders[m])}catch(n){c.log("setRequestHeader in xhr error : "),
c.log(n)}i.send(g.hasContent&&g.data||null);!g.async||4==i.readyState?b._callback():d&&i instanceof d?(i.onload=function(){i.readyState=4;i.status=200;b._callback()},i.onerror=function(){i.readyState=4;i.status=500;b._callback()}):i.onreadystatechange=function(){b._callback()}},abort:function(){this._callback(0,1)},_callback:function(b,e){try{var g=this.xhr,i=this.xhrObj,l=i.config;if(e||4==g.readyState)if(d&&g instanceof d?(g.onerror=c.noop,g.onload=c.noop):g.onreadystatechange=c.noop,e)4!==g.readyState&&
g.abort();else{var m=g.status;if(!(d&&g instanceof d))i.responseHeadersString=g.getAllResponseHeaders();var n=g.responseXML;if(n&&n.documentElement)i.responseXML=n;i.responseText=g.responseText;try{var o=g.statusText}catch(p){c.log("xhr statustext error : "),c.log(p),o=""}!m&&a.isLocal&&!l.crossDomain?m=i.responseText?200:404:1223===m&&(m=204);i.callback(m,o)}}catch(r){g.onreadystatechange=c.noop,e||i.callback(-1,r)}}});a.setupTransport("*",i);return a}},{requires:["./base","./xdr"]});
KISSY.add("ajax/script",function(c,a){function g(c){if(!c.config.crossDomain&&!c.config.forceScript)return new (a.getTransport("*"))(c);this.xhrObj=c;return 0}var e=document;a.setupConfig({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{text:{script:function(a){c.globalEval(a);return a}}}});c.augment(g,{send:function(){var a=this,b,c=this.xhrObj.config,f=e.head||e.getElementsByTagName("head")[0]||
e.documentElement;a.head=f;b=e.createElement("script");a.script=b;b.async="async";if(c.scriptCharset)b.charset=c.scriptCharset;b.src=c.url;b.onerror=b.onload=b.onreadystatechange=function(b){b=b||window.event;a._callback((b.type||"error").toLowerCase())};f.insertBefore(b,f.firstChild)},_callback:function(a,b){var c=this.script,e=this.xhrObj,g=this.head;if(c&&(b||!c.readyState||/loaded|complete/.test(c.readyState)||"error"==a))c.onerror=c.onload=c.onreadystatechange=null,g&&c.parentNode&&g.removeChild(c),
this.head=this.script=void 0,!b&&"error"!=a?e.callback(200,"success"):"error"==a&&e.callback(500,"scripterror")},abort:function(){this._callback(0,1)}});a.setupTransport("script",g);return a},{requires:["./base","./xhr"]});
KISSY.add("ajax/jsonp",function(c,a){a.setupConfig({jsonp:"callback",jsonpCallback:function(){return c.guid("jsonp")}});a.on("start",function(a){var a=a.xhr,e=a.config;if("jsonp"==e.dataType[0]){var d,b=e.jsonpCallback,i=c.isFunction(b)?b():b,f=window[i];e.url+=(/\?/.test(e.url)?"&":"?")+e.jsonp+"="+i;window[i]=function(a){1<arguments.length&&(a=c.makeArray(arguments));d=[a]};a.on("complete",function(){window[i]=f;if(void 0===f)try{delete window[i]}catch(a){}else d&&f(d[0])});a.converters=a.converters||
{};a.converters.script=a.converters.script||{};a.converters.script.json=function(){d||c.error(" not call jsonpCallback : "+i);return d[0]};e.dataType.length=2;e.dataType[0]="script";e.dataType[1]="json"}});return a},{requires:["./base"]});
KISSY.add("ajax/form",function(c,a,g,e){a.on("start",function(a){a=a.xhr.config;if(a.form){var b=g.get(a.form);if("multipart/form-data"!=(b.encoding||b.enctype).toLowerCase()){if(b=e.serialize(b))a.hasContent?(a.data=a.data||"",a.data&&(a.data+="&"),a.data+=b):a.url+=(/\?/.test(a.url)?"&":"?")+b}else b=a.dataType[0],"*"==b&&(b="text"),a.dataType.length=2,a.dataType[0]="iframe",a.dataType[1]=b}});return a},{requires:["./base","dom","./form-serializer"]});
KISSY.add("ajax/iframe-upload",function(c,a,g,e){function d(a){this.xhr=a}var b=document;e.setupConfig({converters:{iframe:e.getConfig().converters.text,text:{iframe:function(a){return a}}}});c.augment(d,{send:function(){var d=this.xhr,e=d.config,h,j=a.get(e.form);this.attrs={target:a.attr(j,"target")||"",action:a.attr(j,"action")||""};this.form=j;var k=c.guid("ajax-iframe");d.iframe=a.create("<iframe  id='"+k+"' name='"+k+"' style='position:absolute;left:-9999px;top:-9999px;'/>");d.iframeId=k;a.prepend(d.iframe,
b.body||b.documentElement);a.attr(j,{target:d.iframeId,action:e.url});if(e.data){h=e.data;e=e.serializeArray;h=c.unparam(h);var k=[],l;for(l in h)for(var m=c.isArray(h[l]),n=c.makeArray(h[l]),o=0;o<n.length;o++){var p=b.createElement("input");p.type="hidden";p.name=l+(m&&e?"[]":"");p.value=n[o];a.append(p,j);k.push(p)}h=k}this.fields=h;g.on(d.iframe,"load error",this._callback,this);j.submit()},_callback:function(b){var c=this.xhr,b=b.type,d=c.iframe;if(d)a.attr(this.form,this.attrs),"load"==b?(b=
d.contentWindow.document,c.responseXML=b,c.responseText=a.text(b.body),c.callback(200,"success")):"error"==b&&c.callback(500,"error"),a.remove(this.fields),g.detach(d),setTimeout(function(){a.remove(d)},30),c.iframe=null},abort:function(){this._callback(0,1)}});e.setupTransport("iframe",d);return e},{requires:["dom","event","./base"]});
KISSY.add("ajax",function(c,a,g){c.mix(g,{serialize:a.serialize,get:function(a,d,b,i,f){c.isFunction(d)&&(i=b,b=d,d=void 0);return g({type:f||"get",url:a,data:d,success:b,dataType:i})},post:function(a,d,b,i){c.isFunction(d)&&(i=b,b=d,d=void 0);return g.get(a,d,b,i,"post")},jsonp:function(a,d,b){c.isFunction(d)&&(b=d,d=void 0);return g.get(a,d,b,"jsonp")},getScript:c.getScript,getJSON:function(a,d,b){c.isFunction(d)&&(b=d,d=void 0);return g.get(a,d,b,"json")},upload:function(a,d,b,i,f){c.isFunction(b)&&
(f=i,i=b,b=void 0);return g({url:a,type:"post",dataType:f,form:d,data:b,success:i})}});return g},{requires:"ajax/form-serializer,ajax/base,ajax/xhrobject,ajax/xhr,ajax/script,ajax/jsonp,ajax/form,ajax/iframe-upload".split(",")});
KISSY.add("base/attribute",function(c,a){function g(){this.__attrs={};this.__attrVals={}}function e(a){a+="";return a.charAt(0).toUpperCase()+a.substring(1)}c.augment(g,{__getDefAttrs:function(){return c.clone(this.__attrs)},addAttr:function(a,b,e){this.__attrs[a]?c.mix(this.__attrs[a],b,e):this.__attrs[a]=c.clone(b||{});return this},addAttrs:function(a,b){var e=this;c.each(a,function(a,c){if(c in b)a.value=b[c];e.addAttr(c,a)});return e},hasAttr:function(a){return a&&this.__attrs.hasOwnProperty(a)},
removeAttr:function(a){this.hasAttr(a)&&(delete this.__attrs[a],delete this.__attrVals[a]);return this},set:function(a,b){var c=this.get(a);if(!(c===b||!1===this.__fireAttrChange("before",a,c,b)))return this.__set(a,b),this.__fireAttrChange("after",a,c,this.__attrVals[a]),this},__fireAttrChange:function(a,b,c,f){return this.fire(a+e(b)+"Change",{attrName:b,prevVal:c,newVal:f})},__set:function(c,b){var e,f=(this.__attrs[c]=this.__attrs[c]||{}).setter;f&&(e=f.call(this,b));e!==a&&(b=e);this.__attrVals[c]=
b},get:function(a){var b;b=(b=this.__attrs[a])&&b.getter;a=a in this.__attrVals?this.__attrVals[a]:this.__getDefAttrVal(a);b&&(a=b.call(this,a));return a},__getDefAttrVal:function(c){var c=this.__attrs[c],b;if(c){if(b=c.valueFn){b=b.call(this);if(b!==a)c.value=b;delete c.valueFn}return c.value}},reset:function(a){if(this.hasAttr(a))return this.set(a,this.__getDefAttrVal(a));for(a in this.__attrs)this.hasAttr(a)&&this.reset(a);return this}});g.__capitalFirst=e;return g});
KISSY.add("base/base",function(c,a,g){function e(c){a.call(this);for(var b=this.constructor;b;){var e=b.ATTRS;if(e){var f=void 0;for(f in e)e.hasOwnProperty(f)&&this.addAttr(f,e[f],!1)}b=b.superclass?b.superclass.constructor:null}if(c)for(var g in c)c.hasOwnProperty(g)&&this.__set(g,c[g])}c.augment(e,g.Target,a);return e},{requires:["./attribute","event"]});KISSY.add("base",function(c,a){return a},{requires:["base/base"]});
KISSY.add("cookie/base",function(c){var a=document,g=encodeURIComponent,e=decodeURIComponent;return{get:function(d){var b,g;if(c.isString(d)&&""!==d&&(g=(""+a.cookie).match(RegExp("(?:^| )"+d+"(?:(?:=([^;]*))|;|$)"))))b=g[1]?e(g[1]):"";return b},set:function(d,b,e,f,h,j){var b=""+g(b),k=e;"number"===typeof k&&(k=new Date,k.setTime(k.getTime()+864E5*e));k instanceof Date&&(b+="; expires="+k.toUTCString());c.isString(f)&&""!==f&&(b+="; domain="+f);c.isString(h)&&""!==h&&(b+="; path="+h);j&&(b+="; secure");
a.cookie=d+"="+b},remove:function(a,b,c,e){this.set(a,"",-1,b,c,e)}}});KISSY.add("cookie",function(c,a){return a},{requires:["cookie/base"]});KISSY.add("core",function(c,a,g,e,d,b,i,f,h,j){i.getScript=c.getScript;a={UA:a,DOM:g,Event:e,EventTarget:e.Target,EventObject:e.Object,Node:d,NodeList:d,JSON:b,Ajax:i,IO:i,ajax:i,io:i,jsonp:i.jsonp,Anim:f,Easing:f.Easing,Base:h,Cookie:j,one:d.one,all:d.all,get:g.get,query:g.query};c.mix(c,a);return a},{requires:"ua,dom,event,node,json,ajax,anim,base,cookie".split(",")});
KISSY.use("core");
