
/*
 * 
 */

package com.xia.jobs.ws.autogen.attention;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri May 25 08:59:04 CST 2012
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "MyAttentionService", 
                  targetNamespace = "http://work.eac.cn/MyAttentionService/") 
public class MyAttentionService extends Service {

    //public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://work.eac.cn/MyAttentionService/", "MyAttentionService");
    public final static QName MyAttentionServiceSOAP = new QName("http://work.eac.cn/MyAttentionService/", "MyAttentionServiceSOAP");

    public MyAttentionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyAttentionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

   /* public MyAttentionService() {
        super(WSDL_LOCATION, SERVICE);
    }*/

    /**
     * 
     * @return
     *     returns MyAttentionServicePortType
     */
    @WebEndpoint(name = "MyAttentionServiceSOAP")
    public MyAttentionServicePortType getMyAttentionServiceSOAP() {
        return super.getPort(MyAttentionServiceSOAP, MyAttentionServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyAttentionServicePortType
     */
    @WebEndpoint(name = "MyAttentionServiceSOAP")
    public MyAttentionServicePortType getMyAttentionServiceSOAP(WebServiceFeature... features) {
        return super.getPort(MyAttentionServiceSOAP, MyAttentionServicePortType.class, features);
    }

}
